# Generated by Django 5.2.9 on 2026-01-01 17:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVCProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_completed', models.PositiveIntegerField(default=0, verbose_name='عدد الكلمات المكتملة')),
                ('words_total_score', models.PositiveIntegerField(default=0, verbose_name='مجموع نقاط الكلمات')),
                ('sentences_completed', models.PositiveIntegerField(default=0, verbose_name='عدد الجمل المكتملة')),
                ('sentences_total_score', models.PositiveIntegerField(default=0, verbose_name='مجموع نقاط الجمل')),
                ('best_reading_time', models.FloatField(blank=True, null=True, verbose_name='أفضل وقت قراءة (ثواني)')),
                ('stories_completed', models.PositiveIntegerField(default=0, verbose_name='عدد القصص المكتملة')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='المجموع الكلي')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
            ],
            options={
                'verbose_name': 'تقدم CVC',
                'verbose_name_plural': 'تقدم CVC',
            },
        ),
        migrations.CreateModel(
            name='CVCSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(help_text='مثل: The cat sat on the mat.', verbose_name='الجملة الإنجليزية')),
                ('arabic_translation', models.TextField(verbose_name='الترجمة العربية')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='مستوى الصعوبة')),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='الوقت المخصص لقراءة الجملة', verbose_name='الحد الزمني بالثواني')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جملة CVC',
                'verbose_name_plural': 'جمل CVC',
                'ordering': ['order', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='CVCStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان القصة')),
                ('content', models.TextField(help_text='القصة بكلمات CVC بسيطة', verbose_name='محتوى القصة بالإنجليزية')),
                ('arabic_explanation', models.TextField(help_text='ترجمة أو شرح القصة للأطفال', verbose_name='الشرح بالعربي')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='رابط صورة القصة')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='مستوى الصعوبة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قصة CVC',
                'verbose_name_plural': 'قصص CVC',
                'ordering': ['order', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='CVCWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10, unique=True, verbose_name='الكلمة')),
                ('arabic_meaning', models.CharField(max_length=100, verbose_name='المعنى بالعربي')),
                ('image_url', models.URLField(blank=True, help_text='رابط صورة توضيحية للكلمة', max_length=500, verbose_name='رابط الصورة')),
                ('category', models.CharField(blank=True, help_text='مثل: animals, food, objects', max_length=50, verbose_name='التصنيف')),
                ('difficulty_level', models.PositiveSmallIntegerField(default=1, help_text='1=سهل جداً، 5=صعب', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='مستوى الصعوبة')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور الكلمة', verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'كلمة CVC',
                'verbose_name_plural': 'كلمات CVC',
                'ordering': ['order', 'word'],
            },
        ),
        migrations.AlterModelOptions(
            name='letterprogress',
            options={'verbose_name': 'تقدم حرف', 'verbose_name_plural': 'تقدم الحروف'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-total_score', 'name'], 'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AddField(
            model_name='letterprogress',
            name='attempts',
            field=models.PositiveIntegerField(default=0, help_text='كم مرة حاول الطالب اختبار هذا الحرف.', verbose_name='عدد المحاولات'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='letters_completed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد الحروف المكتملة'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_score',
            field=models.PositiveIntegerField(default=0, help_text='إجمالي النقاط من جميع الحروف، يُحدّث تلقائياً.', verbose_name='مجموع النقاط'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='letterprogress',
            name='letter',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], db_index=True, max_length=1, verbose_name='الحرف'),
        ),
        migrations.AlterField(
            model_name='letterprogress',
            name='passed',
            field=models.BooleanField(default=False, help_text='True إذا تجاوز الحد المطلوب للنجاح في هذا الحرف.', verbose_name='ناجح في الحرف؟'),
        ),
        migrations.AlterField(
            model_name='letterprogress',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='الدرجة من 0 إلى 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درجة الحرف'),
        ),
        migrations.AlterField(
            model_name='letterprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='phonics.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='letterprogress',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=200, verbose_name='المدرسة'),
        ),
        migrations.AddIndex(
            model_name='letterprogress',
            index=models.Index(fields=['student', 'letter'], name='phonics_let_student_b6c590_idx'),
        ),
        migrations.AddIndex(
            model_name='letterprogress',
            index=models.Index(fields=['letter'], name='phonics_let_letter_b0d0e5_idx'),
        ),
        migrations.AddField(
            model_name='cvcprogress',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cvc_progress', to='phonics.student', verbose_name='الطالب'),
        ),
    ]
