# Generated by Django 5.2.9 on 2026-01-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0002_cvcprogress_cvcsentence_cvcstory_cvcword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvcword',
            name='vowel_sound',
            field=models.CharField(blank=True, db_index=True, default='', help_text='مثل: a, e, i, o, u', max_length=5, verbose_name='صوت حرف العلة'),
        ),
        migrations.AddField(
            model_name='cvcword',
            name='word_family',
            field=models.CharField(blank=True, db_index=True, default='', help_text='مثل: at, an, ig, og - النهاية المشتركة', max_length=10, verbose_name='عائلة الكلمة'),
        ),
        migrations.AddIndex(
            model_name='cvcword',
            index=models.Index(fields=['word_family'], name='phonics_cvc_word_fa_9b72c6_idx'),
        ),
        migrations.AddIndex(
            model_name='cvcword',
            index=models.Index(fields=['vowel_sound'], name='phonics_cvc_vowel_s_5d3afc_idx'),
        ),
        migrations.AddIndex(
            model_name='cvcword',
            index=models.Index(fields=['difficulty_level'], name='phonics_cvc_difficu_e487f2_idx'),
        ),
    ]
