# Generated by Django 5.2.9 on 2026-01-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0003_cvcword_vowel_sound_cvcword_word_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvcstory',
            name='quiz_data',
            field=models.JSONField(blank=True, help_text="JSON structure for questions: [{'question': '...', 'options': ['...'], 'correct': 0, 'feedback_ar': '...'}, ...]", null=True, verbose_name='بيانات الاختبار'),
        ),
    ]
