# Generated by Django 5.2.9 on 2026-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0004_cvcstory_quiz_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvcword',
            name='emoji',
            field=models.CharField(blank=True, default='🎯', help_text='رمز تعبيري يمثل الكلمة', max_length=10, verbose_name='الرمز التعبيري'),
        ),
    ]
