# Generated by Django 5.2.9 on 2026-01-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0005_cvcword_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvcsentence',
            name='category',
            field=models.CharField(default='cvc', help_text='مثل: cvc, pronouns', max_length=50, verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='cvcsentence',
            name='emoji',
            field=models.CharField(blank=True, default='📝', help_text='رمز تعبيري للجملة', max_length=10, verbose_name='الرمز التعبيري'),
        ),
        migrations.AddField(
            model_name='cvcsentence',
            name='quiz_data',
            field=models.JSONField(blank=True, help_text='سؤال يظهر بعد الجملة', null=True, verbose_name='بيانات الاختبار'),
        ),
    ]
