# Generated by Django 5.2.9 on 2026-01-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0006_cvcsentence_category_cvcsentence_emoji_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopGoalUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الوحدة"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان فرعي"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الوحدة"),
                ),
                (
                    "grade",
                    models.CharField(
                        default="Top Goal 6", max_length=50, verbose_name="الصف"
                    ),
                ),
                (
                    "unit_number",
                    models.IntegerField(default=1, verbose_name="رقم الوحدة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TopGoalSentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english_text", models.TextField(verbose_name="النص الإنجليزي")),
                (
                    "arabic_translation",
                    models.TextField(verbose_name="الترجمة العربية"),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="topgoal/audio/",
                        verbose_name="ملف الصوت",
                    ),
                ),
                (
                    "speaker_name",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً: Speaker 1",
                        max_length=50,
                        verbose_name="اسم المتحدث",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="phonics.topgoalunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "جمل Top Goal",
                "verbose_name_plural": "جمل Top Goal",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TopGoalQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="نص السؤال")),
                (
                    "question_type",
                    models.CharField(
                        choices=[("mcq", "اختيار من متعدد"), ("tf", "صواب/خطأ")],
                        default="mcq",
                        max_length=20,
                        verbose_name="نوع السؤال",
                    ),
                ),
                ("options", models.JSONField(default=list, verbose_name="الخيارات")),
                (
                    "correct_answer",
                    models.CharField(max_length=200, verbose_name="الإجابة الصحيحة"),
                ),
                (
                    "explanation_ar",
                    models.TextField(blank=True, verbose_name="شرح الإجابة بالعربي"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="phonics.topgoalunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "اختبار Top Goal",
                "verbose_name_plural": "اختبارات Top Goal",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TopGoalVocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(max_length=100, verbose_name="الكلمة/المصطلح"),
                ),
                (
                    "arabic_meaning",
                    models.CharField(max_length=100, verbose_name="المعنى بالعربي"),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="الرمز التعبيري"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="رابط الصورة"
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="topgoal/audio/",
                        verbose_name="ملف الصوت",
                    ),
                ),
                (
                    "example_sentence",
                    models.TextField(blank=True, verbose_name="جملة مثال"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabularies",
                        to="phonics.topgoalunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "مفردات Top Goal",
                "verbose_name_plural": "مفردات Top Goal",
                "ordering": ["order"],
            },
        ),
    ]
