# Generated by Django 5.2.9 on 2026-06-25 10:50

import phonics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0007_topgoalunit_topgoalsentence_topgoalquiz_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("O", "O"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("V", "V"),
                            ("W", "W"),
                            ("X", "X"),
                            ("Y", "Y"),
                            ("Z", "Z"),
                        ],
                        db_index=True,
                        max_length=1,
                        verbose_name="Letter",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "activity_url",
                    models.URLField(
                        help_text="Allowed: https://wordwall.net/resource/ or https://wordwall.net/play/",
                        max_length=500,
                        validators=[phonics.models.validate_wordwall_activity_url],
                        verbose_name="Activity URL",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="Premium"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Review status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "External game",
                "verbose_name_plural": "External games",
                "ordering": ["letter", "title"],
                "indexes": [
                    models.Index(
                        fields=["letter", "is_active", "review_status"],
                        name="phonics_ext_letter_ad8ed7_idx",
                    )
                ],
            },
        ),
    ]
