# Generated by Django 5.2.9 on 2026-07-01 19:03

import phonics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0011_bird_tutor_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalgame",
            name="activity_url",
            field=models.URLField(
                help_text="Allowed: Wordwall resource and play links.",
                max_length=500,
                validators=[phonics.models.validate_wordwall_activity_url],
                verbose_name="Activity URL",
            ),
        ),
    ]
