# Generated by Django 5.1.2 on 2026-07-01 21:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0012_alter_externalgame_activity_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="letterprogress",
            name="completed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="letterprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="letterprogress",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="letterprogress",
            name="last_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="letterprogress",
            name="mistakes_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="letterprogress",
            name="quiz_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="letterprogress",
            name="total_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="letterprogress",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="letter_progress_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="letterprogress",
            name="words_practiced_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="letterprogress",
            name="words_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="letterprogress",
            name="writing_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Display name"
            ),
        ),
        migrations.AlterField(
            model_name="letterprogress",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_entries",
                to="phonics.student",
                verbose_name="الطالب",
            ),
        ),
        migrations.AddIndex(
            model_name="letterprogress",
            index=models.Index(
                fields=["user", "letter"], name="phonics_let_user_id_c9509d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="letterprogress",
            index=models.Index(
                fields=["user", "completed"], name="phonics_let_user_id_1e68c1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="letterprogress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "letter"),
                name="unique_user_letter_progress",
            ),
        ),
    ]
