# Generated by Django 5.1.2 on 2026-07-02 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0014_soundpracticeprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundpracticeprogress",
            name="last_vowel_practiced",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="soundpracticeprogress",
            name="practiced_vowels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="soundpracticeprogress",
            name="vowel_lessons_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="soundpracticeprogress",
            name="vowel_mastery_percentage",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="soundpracticeprogress",
            name="vowel_microphone_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="soundpracticeprogress",
            name="vowel_microphone_success",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="soundpracticeprogress",
            name="vowel_quiz_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="soundpracticeprogress",
            name="vowel_quiz_correct",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
