# Generated by Django 5.1.2 on 2026-07-02 14:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0015_soundpracticeprogress_last_vowel_practiced_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CVCReadingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_levels", models.JSONField(blank=True, default=list)),
                ("completed_lessons", models.JSONField(blank=True, default=list)),
                ("completed_families", models.JSONField(blank=True, default=list)),
                ("words_practiced", models.JSONField(blank=True, default=list)),
                ("words_mastered", models.JSONField(blank=True, default=list)),
                ("sentences_read", models.PositiveIntegerField(default=0)),
                ("stories_completed", models.PositiveIntegerField(default=0)),
                ("quiz_attempts", models.PositiveIntegerField(default=0)),
                ("quiz_correct", models.PositiveIntegerField(default=0)),
                ("mic_attempts", models.PositiveIntegerField(default=0)),
                ("mic_success", models.PositiveIntegerField(default=0)),
                ("last_word", models.CharField(blank=True, max_length=80)),
                ("last_family", models.CharField(blank=True, max_length=40)),
                ("last_level", models.CharField(blank=True, max_length=40)),
                (
                    "cvc_mastery_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("needs_review_words", models.JSONField(blank=True, default=list)),
                ("last_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvc_reading_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CVC reading progress",
                "verbose_name_plural": "CVC reading progress",
            },
        ),
    ]
