# Generated by Django 5.1.2 on 2026-07-02 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0016_cvcreadingprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="common_sentences_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="days_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="last_sentence",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="last_sentence_level",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="months_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="numbers_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sentence_best_time_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sentence_mastery_percentage",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sentence_microphone_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sentence_microphone_success",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sentence_quiz_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sentence_quiz_correct",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sentence_total_time_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sentences_mastered",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
