# Generated by Django 5.1.2 on 2026-07-02 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0017_cvcreadingprogress_common_sentences_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="last_story",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="last_story_level",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="stories_started",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="story_best_reading_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="story_mastery_percentage",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="story_microphone_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="story_microphone_success",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="story_needs_review",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="story_quiz_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="story_quiz_correct",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
