# Generated by Django 5.1.2 on 2026-07-02 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0018_cvcreadingprogress_last_story_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="last_pronoun",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="last_pronoun_level",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="pronoun_lessons_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="pronoun_mastery_percentage",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="pronoun_microphone_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="pronoun_microphone_success",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="pronoun_quiz_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="pronoun_quiz_correct",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="pronouns_mastered",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="pronouns_needs_review",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="pronouns_practiced",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
