# Generated by Django 5.1.2 on 2026-07-02 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0019_cvcreadingprogress_last_pronoun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="action_verbs_mastered",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="adjectives_mastered",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="best_reading_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="best_wpm",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="conversations_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="fluency_accuracy",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="fluency_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="fluency_mastery_percentage",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="fluency_score",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="fluency_sentences_read",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="last_conversation",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="last_fluency_sentence",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="last_sight_word",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="question_words_mastered",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sight_word_quiz_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sight_word_quiz_correct",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sight_words_mastered",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cvcreadingprogress",
            name="sight_words_practiced",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
