# Generated by Django 5.2.9 on 2026-07-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0020_cvcreadingprogress_action_verbs_mastered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="grade",
            field=models.CharField(blank=True, max_length=80, verbose_name="الصف"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="grade",
            field=models.CharField(blank=True, max_length=80, verbose_name="الصف"),
        ),
    ]
