# Generated by Django 5.2.9 on 2026-07-05 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0021_student_grade_studentprofile_grade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnglishFoundationProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("vocabulary", "Vocabulary"),
                            ("grammar", "Grammar"),
                            ("conversations", "Conversations"),
                            ("common_sentences", "Common Sentences"),
                            ("worksheets", "Worksheets"),
                            ("games", "Games"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                ("actions_count", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(db_index=True, default=False)),
                ("last_activity_type", models.CharField(blank=True, max_length=80)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="english_foundation_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "English foundation progress",
                "verbose_name_plural": "English foundation progress",
                "ordering": ["user", "section"],
                "indexes": [
                    models.Index(
                        fields=["user", "section"],
                        name="phonics_eng_user_id_1ca076_idx",
                    ),
                    models.Index(
                        fields=["section", "completed"],
                        name="phonics_eng_section_dc7ed4_idx",
                    ),
                ],
                "unique_together": {("user", "section")},
            },
        ),
    ]
