# Generated by Django 5.1.2 on 2026-07-10 12:25

import django.db.models.deletion
import phonics.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0022_englishfoundationprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_code", models.CharField(db_index=True, max_length=60)),
                ("plan_name", models.CharField(max_length=120)),
                ("duration_days", models.PositiveSmallIntegerField(default=30)),
                ("amount_halalas", models.PositiveIntegerField()),
                ("amount_sar", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("initiated", "Initiated"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                            ("awaiting_bank_review", "Awaiting bank review"),
                            ("bank_approved", "Bank approved"),
                            ("bank_rejected", "Bank rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=40,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("moyasar_card", "Moyasar card"),
                            ("moyasar_stcpay", "Moyasar STC Pay"),
                            ("bank_transfer", "Bank transfer"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("moyasar", "Moyasar"),
                            ("manual_bank", "Manual bank"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("provider_status", models.CharField(blank=True, max_length=80)),
                ("checkout_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment order",
                "verbose_name_plural": "Payment orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankTransferProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=120)),
                ("sender_name", models.CharField(max_length=160)),
                (
                    "sender_account_last_digits",
                    models.CharField(blank=True, max_length=8),
                ),
                ("transfer_reference", models.CharField(blank=True, max_length=120)),
                ("transferred_at", models.DateField()),
                ("amount_sar", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "receipt_file",
                    models.FileField(
                        upload_to=phonics.models.bank_transfer_receipt_upload_to,
                        validators=[phonics.models.validate_bank_transfer_receipt],
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=30,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_bank_transfer_proofs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transfer_proofs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_proofs",
                        to="phonics.paymentorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank transfer proof",
                "verbose_name_plural": "Bank transfer proofs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_code", models.CharField(db_index=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                            ("pending_payment", "Pending payment"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=30,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activated_by_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activated_subscriptions",
                        to="phonics.paymentorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User subscription",
                "verbose_name_plural": "User subscriptions",
            },
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(
                fields=["user", "status"], name="phonics_pay_user_id_5d025c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(
                fields=["plan_code", "status"], name="phonics_pay_plan_co_cae002_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(
                fields=["provider", "provider_payment_id"],
                name="phonics_pay_provide_4e7606_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransferproof",
            index=models.Index(
                fields=["user", "status"], name="phonics_ban_user_id_508f77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransferproof",
            index=models.Index(
                fields=["payment_order", "status"],
                name="phonics_ban_payment_23ae64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["user", "status", "expires_at"],
                name="phonics_use_user_id_9fac58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["plan_code", "status"], name="phonics_use_plan_co_c6c1e3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersubscription",
            constraint=models.UniqueConstraint(
                fields=("user", "plan_code"), name="unique_user_subscription_plan"
            ),
        ),
    ]
