# Generated by Django 5.1.2 on 2026-07-12 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0023_payment_checkout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="banktransferproof",
            index=models.Index(
                fields=["status", "created_at"], name="bank_proof_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="birdreviewitem",
            index=models.Index(
                fields=["user", "mastered", "-updated_at", "letter", "word"],
                name="bird_review_user_queue_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cvcreadingprogress",
            index=models.Index(fields=["updated_at"], name="cvc_reading_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="cvcsentence",
            index=models.Index(
                fields=["order", "id"], name="cvc_sentence_order_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cvcsentence",
            index=models.Index(
                fields=["category", "order", "difficulty"],
                name="cvc_sentence_sheet_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cvcstory",
            index=models.Index(fields=["order", "id"], name="cvc_story_order_id_idx"),
        ),
        migrations.AddIndex(
            model_name="cvcstory",
            index=models.Index(
                fields=["order", "difficulty"], name="cvc_story_sheet_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cvcword",
            index=models.Index(fields=["order", "id"], name="cvc_word_order_id_idx"),
        ),
        migrations.AddIndex(
            model_name="cvcword",
            index=models.Index(
                fields=["vowel_sound", "word_family", "order", "word"],
                name="cvc_word_sheet_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="englishfoundationprogress",
            index=models.Index(
                fields=["last_activity_at"], name="english_progress_last_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="englishfoundationprogress",
            index=models.Index(
                fields=["user", "last_activity_at"],
                name="english_progress_user_last_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="letterprogress",
            index=models.Index(
                fields=["student", "timestamp"], name="letter_student_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="letterprogress",
            index=models.Index(
                fields=["user", "last_updated_at"], name="letter_user_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(
                fields=["status", "created_at"], name="payment_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(
                fields=["method", "status", "created_at"],
                name="payment_method_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["-total_score", "name"], name="student_score_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["grade", "name"], name="student_grade_name_idx"),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["grade"], name="student_profile_grade_idx"),
        ),
        migrations.AddIndex(
            model_name="topgoalquiz",
            index=models.Index(
                fields=["unit", "order"], name="topgoal_quiz_unit_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topgoalsentence",
            index=models.Index(
                fields=["unit", "order"], name="topgoal_sent_unit_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topgoalunit",
            index=models.Index(
                fields=["grade", "unit_number"], name="topgoal_unit_grade_num_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topgoalvocabulary",
            index=models.Index(
                fields=["unit", "order"], name="topgoal_vocab_unit_order_idx"
            ),
        ),
    ]
