# Generated by Django 5.2.9 on 2026-07-19 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonics", "0025_strengthen_moyasar_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="invoice_creation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="invoice_creation_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("creating_invoice", "Creating invoice"),
                    ("invoice_creation_unknown", "Invoice creation unknown"),
                    ("initiated", "Initiated"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                    ("canceled", "Canceled"),
                    ("awaiting_bank_review", "Awaiting bank review"),
                    ("bank_approved", "Bank approved"),
                    ("bank_rejected", "Bank rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="moyasar", max_length=40)),
                ("event_id", models.CharField(max_length=120, unique=True)),
                ("event_type", models.CharField(max_length=80)),
                (
                    "payment_environment",
                    models.CharField(
                        choices=[("test", "Test"), ("live", "Live")],
                        default="test",
                        max_length=10,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("pending", "Pending"),
                            ("mismatch", "Mismatch"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=30,
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "payment_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="phonics.paymentorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "processing_status", "received_at"],
                        name="webhook_provider_status_idx",
                    ),
                    models.Index(
                        fields=["payment_order", "received_at"],
                        name="webhook_order_received_idx",
                    ),
                ],
            },
        ),
    ]
