# Generated by Django 5.2.9 on 2026-07-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonics", "0026_add_moyasar_reconciliation_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="amount_due",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="current_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="from_plan_code",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("renewal", "Renewal"),
                    ("upgrade", "Upgrade"),
                ],
                db_index=True,
                default="purchase",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="original_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="target_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="to_plan_code",
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
