# Generated by Django 5.2.9 on 2026-07-20 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonics", "0028_studentprofile_city_and_phone_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("creating_invoice", "Creating invoice"),
                    ("invoice_creation_unknown", "Invoice creation unknown"),
                    ("initiated", "Initiated"),
                    ("paid", "Paid"),
                    ("paid_requires_review", "Paid - requires review"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                    ("canceled", "Canceled"),
                    ("awaiting_bank_review", "Awaiting bank review"),
                    ("bank_approved", "Bank approved"),
                    ("bank_rejected", "Bank rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="PaymentActivationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason_code", models.CharField(db_index=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("resolved", "Resolved")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation_review",
                        to="phonics.paymentorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="payment_review_status_idx",
                    )
                ],
            },
        ),
    ]
