# Generated by Django 5.2.9 on 2026-08-07 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonics", "0029_add_payment_activation_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=80)),
                ("target_model", models.CharField(db_index=True, max_length=120)),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("target_repr", models.CharField(blank=True, max_length=255)),
                ("before_status", models.JSONField(blank=True, default=dict)),
                ("after_status", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "provider_event_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_operations_dashboard", "Can view the operations dashboard"),
                    ("run_payment_reconciliation", "Can run payment reconciliation"),
                ],
            },
        ),
    ]
