from english_path.services.unit_schema import validate_unit
from english_path.services.units.factory import activity_question as aq, build_unit as b, quiz_question as q, vocab as v

VOCAB = (
    v("mother", "أم", "My mother is a teacher.", "أمي معلمة.", "family"), v("father", "أب", "My father is kind.", "أبي لطيف.", "family"),
    v("sister", "أخت", "I have one sister.", "لدي أخت واحدة.", "family"), v("brother", "أخ", "His brother is ten.", "أخوه عمره عشر سنوات.", "family"),
    v("parents", "الوالدان", "My parents are at home.", "والداي في المنزل.", "family"), v("grandmother", "جدة", "Her grandmother is Sara.", "جدتها سارة.", "family"),
    v("grandfather", "جد", "My grandfather has a farm.", "جدي لديه مزرعة.", "family"), v("family", "عائلة", "We are a big family.", "نحن عائلة كبيرة.", "family"),
    v("son", "ابن", "He is their son.", "هو ابنهما.", "family"), v("daughter", "ابنة", "She is our daughter.", "هي ابنتنا.", "family"),
)
GRAMMAR = {"title":"have / has + possessive adjectives","explanation_en":"Use have with I/you/we/they and has with he/she/it. My, your, his and her show who something belongs to.","explanation_ar":"نستخدم have مع I/you/we/they وhas مع he/she/it. وتوضح my/your/his/her الملكية.","examples":("I have two brothers.","Mona has one sister.","His father is a doctor.","Her mother is kind."),"common_mistakes":("She have a sister. → She has a sister.","He has her brother. → He has a brother.","I name is Ali. → My name is Ali."),"tips":("ابحث عن الفاعل قبل اختيار have أو has.","his لولد وher لبنت.")}
LISTENING = {"dialogue":(("Lina","This is my family photo."),("Omar","Who is this?"),("Lina","She is my mother, Huda. She has two daughters."),("Omar","Is this your brother?"),("Lina","Yes. His name is Sami. He is nine.")),"audio_text":"This is my family photo. She is my mother Huda. She has two daughters. This is my brother. His name is Sami. He is nine.","transcript":(("Lina","This is my family photo."),("Omar","Who is this?"),("Lina","She is my mother, Huda. She has two daughters."),("Omar","Is this your brother?"),("Lina","Yes. His name is Sami. He is nine.")),"hide_transcript_until_attempt":True,"questions":(aq("Who is Huda?",("Lina’s mother","Lina’s sister","Lina’s grandmother"),"Lina’s mother"),aq("How many daughters does Huda have?",("one","two","three"),"two"),aq("What is the brother’s name?",("Omar","Sami","Ali"),"Sami"))}
SPEAKING = {"shadowing":("This is my family.","I have one brother and two sisters.","Her name is Huda.","My parents are kind."),"pronunciation_practice":("mother /ˈmʌðər/","father /ˈfɑːðər/","family /ˈfæməli/"),"role_play":(("Friend","Who is in this photo?"),("You","This is my …"),("Friend","What is his or her name?"),("You","His/Her name is …")),"prompts":("Show or imagine a family photo.","Ask one question about your partner’s family.")}
READING = {"title":"Noura’s family","passage":"Noura has a small family. Her father is Faisal and her mother is Reem. Noura has one brother. His name is Zaid, and he is seven. Her grandmother lives near their home. They visit her every Friday.","arabic_support":"مساعدة: تعيش الجدة بالقرب من منزلهم.","questions":(aq("Is Noura’s family big or small?",("big","small","not stated"),"small"),aq("Who is Zaid?",("her father","her brother","her grandfather"),"her brother"),aq("When do they visit the grandmother?",("Friday","Saturday","Sunday"),"Friday"))}
WRITING = {"task":"Write five sentences about your family.","model":"I have a small family. My father is Khalid. My mother is Amal. I have one sister. Her name is Dana.","checklist":("Use have/has correctly.","Use my/his/her.","Begin names with capital letters."),"scaffold":("I have a ___ family.","My father is ___.","I have ___ brother(s).","His/Her name is ___.")}
MISSION = {"title":"Introduce Your Family","real_world_task":"Use a photo or drawing to introduce at least three family members.","steps":("Introduce your family.","Name three people.","Use have or has.","Use his or her once.","Answer one question."),"success_criteria":("I can name family members.","I can show possession clearly.")}
QUIZ = (
q("v1","vocabulary","family-members",1,"Your father and mother are your ___.",("parents","brothers","friends"),"parents","Parents means your mother and father together.","فكر في كلمة تجمع الأم والأب.",( "Your sons and daughters are your ___.",("children","parents","friends"),"children","Children تجمع الأبناء والبنات.")),
q("v2","vocabulary","family-members",2,"My mother’s mother is my ___.",("sister","grandmother","daughter"),"grandmother","أم الأم هي الجدة.","تتبع العلاقة العائلية خطوة خطوة.",( "My father’s father is my ___.",("grandfather","brother","son"),"grandfather","أبو الأب هو الجد.")),
q("g1","grammar","have-has",2,"Mona ___ two sisters.",("have","has","having"),"has","Mona مفرد غائب، لذلك نستخدم has.","Mona يمكن استبدالها بـ she.",( "Ali ___ one brother.",("have","has","is"),"has","Ali = he، ومع he نستخدم has.")),
q("g2","grammar","have-has",2,"We ___ a big family.",("has","have","is"),"have","مع We نستخدم have.","حدد الفاعل We.",( "They ___ two sons.",("has","have","are"),"have","مع They نستخدم have.")),
q("g3","grammar","possessive-adjectives",3,"Ahmed has a sister. ___ name is Hala.",("His","Her","My"),"Her","الاسم يعود إلى sister وهي مؤنث، لذا Her.","حدد صاحب الاسم مباشرة.",( "Sara has a brother. ___ name is Omar.",("Her","His","Your"),"His","الاسم يعود إلى brother وهو مذكر، لذا His.")),
q("l1","listening","family-detail",2,"Listen: My father is a teacher. What is his job?",("doctor","teacher","student"),"teacher","المتحدث قال teacher مباشرة.","استمع إلى الكلمة بعد is a.",( "Listen: Her mother is a doctor. What is her job?",("doctor","teacher","student"),"doctor","الكلمة المسموعة هي doctor.")),
q("l2","listening","numbers",3,"Listen: I have two brothers and one sister. How many brothers?",("one","two","three"),"two","الجملة ذكرت two قبل brothers.","اربط الرقم بالاسم الذي يليه.",( "Listen: I have three sisters. How many sisters?",("two","three","four"),"three","العدد المذكور هو three.")),
q("r1","reading","detail",2,"Reem has one son, Sami. Who is Sami?",("her son","her father","her brother"),"her son","النص يقول مباشرة one son, Sami.","ابحث عن الاسم بعد son.",( "Huda has one daughter, Lina. Who is Lina?",("her mother","her daughter","her sister"),"her daughter","Lina هي الابنة المذكورة.")),
q("w1","writing","sentence",3,"Choose the correct sentence.",("She have a brother.","She has a brother.","She has brother."),"She has a brother.","She تحتاج has، والاسم المفرد brother يحتاج a.","تحقق من الفعل وأداة الاسم.",( "Choose the correct sentence.",("He have a sister.","He has a sister.","He has sister."),"He has a sister.","He يأخذ has وsister المفردة تأخذ a.")),
q("s1","speaking","response",2,"Someone asks: Who is she?",("She is my sister.","I have twelve.","His name is Sara."),"She is my sister.","هذا الرد يعرّف الشخص المؤنث بوضوح.","ابدأ بـ She is.",( "Someone asks: Who is he?",("He is my brother.","Her is brother.","I am father."),"He is my brother.","نستخدم He is للتعريف بشخص مذكر.")),)
UNIT = validate_unit(b(code="A1.2",title="My Family",arabic_title="عائلتي",theme="family-photo",objectives=("Learn family words","Use have and has","Show possession"),can_do=("I can introduce my family.","I can ask who someone is."),vocabulary=VOCAB,grammar=GRAMMAR,listening=LISTENING,speaking=SPEAKING,reading=READING,writing=WRITING,mission=MISSION,quiz=QUIZ))
