"""Authored A1.11-A1.20 expansion using the established rich-unit contract."""

def vocab(word, arabic, example, example_ar, category, collocation="", word_family=""):
    return {
        "word": word, "arabic": arabic, "example": example, "example_ar": example_ar,
        "category": category, "collocation": collocation, "word_family": word_family,
        "audio": {"tts": True, "lang": "en-GB"}, "group": "core",
    }


def check(prompt, choices, answer, reason, *, spoken=""):
    return {"prompt": prompt, "choices": tuple(choices), "answer": answer, "reason": reason, "spoken": spoken}


def _activity(item, question_type="Choose"):
    return {"prompt": item["prompt"], "choices": item["choices"], "answer": item["answer"], "question_type": question_type}


def _quiz_question(qid, skill, subskill, difficulty, item, similar):
    productive = skill not in {"speaking", "writing"}
    result = {
        "id": qid, "skill": skill, "subskill": subskill, "difficulty": difficulty,
        "prompt": item["prompt"], "choices": item["choices"], "answer": item["answer"],
        "explanation_ar": item["reason"], "why_correct": item["reason"],
        "clue": "ارجع إلى نموذج الوحدة وحدد المعنى والفاعل وشكل الجملة.",
        "why_each_wrong": {
            choice: f"الخيار «{choice}» لا يطابق معنى السؤال أو نموذج الوحدة."
            for choice in item["choices"] if choice != item["answer"]
        },
        "similar_question": {
            "prompt": similar["prompt"], "choices": similar["choices"],
            "answer": similar["answer"], "why": similar["reason"],
            **({"spoken": similar["spoken"]} if similar.get("spoken") else {}),
        },
        "productive_score": productive,
    }
    if item.get("spoken"):
        result["spoken"] = item["spoken"]
    if not productive:
        result["assessment_label"] = "Auto-scored language choice — not a productive skill score"
    return result


def build_unit(spec):
    grammar_checks = spec["grammar_checks"]
    vocabulary = spec["vocabulary"]
    vocab_checks = tuple(
        C(
            f"Choose the word for: {item['arabic']}",
            (item["word"], vocabulary[(index + 1) % len(vocabulary)]["word"], vocabulary[(index + 2) % len(vocabulary)]["word"]),
            item["word"],
            f"{item['word']} means {item['arabic']} in this unit.",
        )
        for index, item in enumerate(vocabulary[:3])
    )
    wrong, correct = (part.strip() for part in spec["grammar"]["common_mistakes"][0].split("→", 1))
    grammar = {
        **spec["grammar"],
        "practice": (
            {"stage": "Choose", **{key: grammar_checks[0][key] for key in ("prompt", "choices", "answer")}},
            {"stage": "Complete", **{key: grammar_checks[1][key] for key in ("prompt", "choices", "answer")}},
            {"stage": "Build sentence", "prompt": "Build the model sentence.", "target": spec["grammar"]["examples"][0], "tokens": tuple(reversed(spec["grammar"]["examples"][0].split()))},
            {"stage": "Correct mistake", "prompt": f"Correct: {wrong}", "choices": (wrong, correct), "answer": correct},
            {"stage": "Use it in context", **{key: grammar_checks[2][key] for key in ("prompt", "choices", "answer")}},
        ),
    }
    listening_checks = spec["listening_checks"]
    reading_checks = spec["reading_checks"]
    quiz = (
        _quiz_question("v1", "vocabulary", spec["vocab_subskill"], 2, vocab_checks[0], vocab_checks[1]),
        _quiz_question("v2", "vocabulary", spec["vocab_subskill"], 2, vocab_checks[1], vocab_checks[2]),
        _quiz_question("g1", "grammar", spec["grammar_subskill"], 2, grammar_checks[0], grammar_checks[1]),
        _quiz_question("g2", "grammar", spec["grammar_subskill"], 3, grammar_checks[1], grammar_checks[2]),
        _quiz_question("g3", "grammar", spec["grammar_subskill"], 3, grammar_checks[2], grammar_checks[0]),
        _quiz_question("l1", "listening", spec["listening_subskill"], 2, listening_checks[0], listening_checks[1]),
        _quiz_question("l2", "listening", spec["listening_subskill"], 3, listening_checks[1], listening_checks[2]),
        _quiz_question("r1", "reading", "detail", 3, reading_checks[0], reading_checks[1]),
        _quiz_question("w1", "writing", "sentence-choice", 3, spec["writing_check"], spec["writing_similar"]),
        _quiz_question("s1", "speaking", "functional-response", 2, spec["speaking_check"], spec["speaking_similar"]),
    )
    extra_game = spec["extra_game"]
    return {
        "code": spec["code"], "level": "A1", "order": spec["order"],
        "title": spec["title"], "arabic_title": spec["arabic_title"], "theme": spec["theme"],
        "objectives": spec["objectives"], "can_do_statements": spec["can_do"],
        "review_from": spec["review_from"], "arabic_support": "on-demand", "phase3_version": 1,
        "vocabulary": spec["vocabulary"], "useful_expressions": spec["expressions"],
        "spiral_review": {"ratio": "80/20", "items": tuple({key: item[key] for key in ("prompt", "choices", "answer")} for item in spec["review_checks"])},
        "grammar": grammar,
        "listening": {
            "dialogue": spec["dialogue"], "audio_text": " ".join(line for _, line in spec["dialogue"]),
            "transcript": spec["dialogue"], "hide_transcript_until_attempt": True,
            "questions": tuple(_activity(item) for item in listening_checks),
            "gist_question": {key: spec["gist"][key] for key in ("prompt", "choices", "answer")},
            "stages": ("Listen for the main idea.", "Listen for key words and details.", "Listen again, answer, then check the transcript."),
        },
        "speaking": {
            "shadowing": spec["shadowing"], "pronunciation_practice": spec["pronunciation"],
            "role_play": spec["role_play"], "prompts": spec["speaking_prompts"],
            "answer_question": spec["speaking_question"], "mini_challenge": spec["speaking_challenge"],
            "pronunciation_focus": {"title": spec["pronunciation_focus"], "tip": spec["pronunciation_tip"]},
            "rubric": ("Meaning", "Target language", "Clarity", "Completion"),
        },
        "reading": {
            "title": spec["reading_title"], "passage": spec["reading_passage"],
            "arabic_support": spec["reading_help"], "strategy": "Read once for the main idea. Read again and find the exact clue.",
            "questions": tuple(_activity(item, kind) for item, kind in zip(reading_checks, spec["reading_types"])),
        },
        "writing": {
            "task": spec["writing_task"], "model": spec["writing_model"], "checklist": spec["writing_checklist"],
            "scaffold": spec["writing_guided"], "guided": spec["writing_guided"],
            "semi_guided": spec["writing_semi"], "independent": spec["writing_task"], "productive_practice": True,
        },
        "games": (
            {"id": "word-match", "type": "word_match", "title": "Word Match", "goal": "Match key words to their meanings."},
            {"id": "sentence-builder", "type": "sentence_builder", "title": "Sentence Builder", "goal": grammar["examples"][0]},
            {"id": "missing-word", "type": "missing_word", "title": "Missing Word", "goal": grammar_checks[0]["reason"], **{key: grammar_checks[0][key] for key in ("prompt", "choices", "answer")}},
            {"id": extra_game["id"], "type": extra_game["type"], "title": extra_game["title"], "goal": extra_game["reason"], **{key: extra_game[key] for key in ("prompt", "choices", "answer")}, **({"spoken": extra_game["spoken"]} if extra_game.get("spoken") else {})},
        ),
        "mission": {
            "title": spec["mission_title"], "real_world_task": spec["mission_task"],
            "steps": spec["mission_steps"], "success_criteria": spec["mission_success"],
            "integrated_skills": ("vocabulary", "grammar", "listening", "speaking", "reading", "writing"),
        },
        "quiz": quiz,
        **({"british_english_note": spec["british_note"]} if spec.get("british_note") else {}),
    }


def V(*items):
    return tuple(vocab(*item) for item in items)


def E(*items):
    return tuple({"expression": text, "arabic": arabic, "example": example} for text, arabic, example in items)


def C(prompt, choices, answer, reason, spoken=""):
    return check(prompt, choices, answer, reason, spoken=spoken)


SPECS = (
    {
        "code":"A1.11","order":11,"title":"Numbers, Days & Dates","arabic_title":"الأرقام والأيام والتواريخ","theme":"calendar-plans",
        "objectives":("Say common numbers and dates","Name days and months","Ask about birthdays"),
        "can_do":("I can say common numbers.","I can name days and months.","I can say a simple date.","I can ask when a birthday is."),
        "review_from":("A1.1","A1.4","A1.10"),
        "vocabulary":V(("eleven","أحد عشر","There are eleven students.","يوجد أحد عشر طالبًا.","number","eleven students",""),("twenty","عشرون","My class has twenty desks.","في صفي عشرون مكتبًا.","number","twenty desks",""),("thirty","ثلاثون","The lesson starts in thirty minutes.","يبدأ الدرس بعد ثلاثين دقيقة.","number","thirty minutes",""),("first","الأول","Monday is the first day on this calendar.","الاثنين هو اليوم الأول في هذا التقويم.","ordinal","the first day",""),("Monday","الاثنين","The class is on Monday.","الحصة يوم الاثنين.","day","on Monday",""),("Friday","الجمعة","We visit our family on Friday.","نزور عائلتنا يوم الجمعة.","day","on Friday",""),("January","يناير","The course starts in January.","تبدأ الدورة في يناير.","month","in January",""),("month","شهر","June is a summer month.","يونيو شهر صيفي.","calendar","this month",""),("date","تاريخ","Write the date at the top.","اكتب التاريخ في الأعلى.","calendar","today’s date",""),("birthday","عيد ميلاد","My birthday is in May.","عيد ميلادي في مايو.","event","birthday date","")),
        "expressions":E(("What day is it?","ما اليوم؟","What day is it today?"),("What’s the date?","ما التاريخ؟","What’s the date today?"),("When is your birthday?","متى عيد ميلادك؟","When is your birthday?"),("It’s on …","إنه في ...","It’s on Friday.")),
        "review_checks":(C("I wake up ___ six.",( "at","on","in"),"at","Use at with clock times."),C("We went to the park ___.",("yesterday","right now","every morning"),"yesterday","Yesterday marks a finished time.")),
        "grammar":{"title":"Dates with on / in · When is …?","explanation_en":"Use on with days and dates, and in with months. Ask When is...? and answer It’s on... or It’s in....","explanation_ar":"نستخدم on مع الأيام والتواريخ، وin مع الأشهر. نسأل When is…? ونجيب It’s on… أو It’s in…","examples":("My birthday is on 12 May.","The holiday is in January.","When is the class?","It’s on Monday."),"common_mistakes":("in Monday → on Monday","on January → in January","When your birthday is? → When is your birthday?"),"tips":("Use capital letters for English days and months.","Say the day before the month in British English: 12 May.")},
        "grammar_checks":(C("The class is ___ Monday.",("on","in","at"),"on","Use on with a day."),C("My birthday is ___ June.",("in","on","at"),"in","Use in with a month."),C("___ your birthday?",("When is","What is when","When are"),"When is","Use When is before a singular event.")),
        "dialogue":(("Maya","What day is the school event?"),("Omar","It’s on Friday, 14 March."),("Maya","What time does it start?"),("Omar","At ten thirty."),("Maya","Great. My birthday is in March too!")),
        "gist":C("What are they mainly discussing?",("a school event date","a food order","a bus route"),"a school event date","They discuss a day, date and time."),
        "listening_checks":(C("What day is the event?",("Friday","Monday","Sunday"),"Friday","The speaker says Friday.","The school event is on Friday."),C("What is the date?",("14 March","4 March","14 May"),"14 March","The speaker says the fourteenth of March.","The date is the fourteenth of March."),C("What time does it start?",("10:30","9:30","11:00"),"10:30","The speaker says ten thirty.","It starts at ten thirty.")),
        "shadowing":("What day is it today?","The event is on Friday.","My birthday is in May.","What’s the date?"),"pronunciation":("thirteen /ˌθɜːˈtiːn/","thirty /ˈθɜːti/","date /deɪt/"),"role_play":(("Partner","When is the event?"),("You","It’s on …"),("Partner","What time does it start?"),("You","It starts at …")),"speaking_prompts":("Say today’s day.","Say one important date."),"speaking_question":"When is your birthday or another important day?","speaking_challenge":"Give a day, date and time for a simple event.","pronunciation_focus":"Teen numbers and tens","pronunciation_tip":"Stress -teen in thirteen; stress the first syllable in thirty.",
        "reading_title":"The class calendar","reading_passage":"Our English club meets on Monday and Wednesday. In April, we have a small show. The show is on 18 April at five o’clock. Lina’s birthday is on 20 April, two days after the show.","reading_help":"مساعدة: two days after تعني بعد يومين.","reading_checks":(C("When does the club meet?",("Monday and Wednesday","Friday only","Tuesday and Thursday"),"Monday and Wednesday","The first sentence names both days."),C("When is the show?",("18 April","20 April","8 April"),"18 April","The passage gives 18 April."),C("Which comes first?",("the show","Lina’s birthday","they are the same day"),"the show","The show is two days before the birthday.")),"reading_types":("Find information","When?","Sequence"),
        "writing_task":"Write 3–5 sentences about two important dates.","writing_model":"My English class is on Monday. It starts at four o’clock. My birthday is in July. It is on 9 July.","writing_checklist":("Use on with a day or date.","Use in with a month.","Begin days and months with capital letters."),"writing_guided":("The class is on ___.","My birthday is in ___."),"writing_semi":("Include one day.","Include one date.","Include one time."),"writing_check":C("Choose the correct sentence.",("My birthday is on 9 May.","My birthday is in Monday.","My birthday on May."),"My birthday is on 9 May.","Use on with a full date."),"writing_similar":C("Choose the correct sentence.",("The course starts in June.","The course starts on June.","Course in starts June."),"The course starts in June.","Use in with a month."),
        "speaking_check":C("When is the meeting?",("It’s on Tuesday.","It Tuesday is.","On is Tuesday."),"It’s on Tuesday.","This is a natural complete answer."),"speaking_similar":C("What’s the date?",("It’s 12 March.","It March on.","Date is what."),"It’s 12 March.","This gives a clear date."),
        "extra_game":{"id":"calendar-order","type":"order_words","title":"Calendar Order","prompt":"Choose the correctly ordered question.","choices":("When is your birthday?","Your birthday when is?","Is birthday your when?"),"answer":"When is your birthday?","reason":"Practise question order."},
        "mission_title":"Plan a Class Event","mission_task":"Choose a day, date and time, then invite a partner.","mission_steps":("Name the event.","Give the day.","Give the date.","Give the time.","Ask if your partner can come."),"mission_success":("I can give clear calendar information.","I can ask and answer When questions."),"british_note":"British date order puts the day before the month: write 12 May and say the twelfth of May.",
        "vocab_subskill":"calendar","grammar_subskill":"dates","listening_subskill":"date-time",
    },
    {
        "code":"A1.12","order":12,"title":"Clothes & Colours","arabic_title":"الملابس والألوان","theme":"getting-ready",
        "objectives":("Name common clothes","Describe colours and size","Say what someone is wearing"),"can_do":("I can name common clothes.","I can describe clothes with colours.","I can say what someone is wearing.","I can ask about an item of clothing."),"review_from":("A1.3","A1.5","A1.7"),
        "vocabulary":V(("shirt","قميص","He is wearing a blue shirt.","هو يرتدي قميصًا أزرق.","clothes","a blue shirt",""),("trousers","بنطال","These trousers are black.","هذا البنطال أسود.","clothes","black trousers",""),("dress","فستان","Her dress is green.","فستانها أخضر.","clothes","a green dress",""),("jacket","سترة","Take your jacket today.","خذ سترتك اليوم.","clothes","a warm jacket",""),("shoes","حذاء","My shoes are brown.","حذائي بني.","clothes","a pair of shoes",""),("hat","قبعة","This red hat is mine.","هذه القبعة الحمراء لي.","clothes","a red hat",""),("wearing","يرتدي","Sara is wearing a dress.","سارة ترتدي فستانًا.","action","wearing a jacket","wear → wearing"),("red","أحمر","I like the red shirt.","أحب القميص الأحمر.","colour","bright red",""),("blue","أزرق","His jacket is blue.","سترته زرقاء.","colour","dark blue",""),("green","أخضر","These shoes are green.","هذا الحذاء أخضر.","colour","light green","")),
        "expressions":E(("What are you wearing?","ماذا ترتدي؟","What are you wearing today?"),("I’m wearing …","أنا أرتدي ...","I’m wearing a blue shirt."),("Which one?","أي واحد؟","Which one is yours?"),("It looks nice.","يبدو جميلًا.","Your jacket looks nice.")),
        "review_checks":(C("___ are my shoes here.",("These","This","That"),"These","Use These for plural things nearby."),C("She is ___ now.",("reading","read","reads"),"reading","Use is plus verb-ing for an action now.")),
        "grammar":{"title":"be wearing · adjective + noun","explanation_en":"Use am/is/are wearing for clothes now. In English, put the colour before the clothing noun.","explanation_ar":"نستخدم am/is/are wearing للملابس الآن. في الإنجليزية يأتي اللون قبل اسم قطعة الملابس.","examples":("I am wearing a blue shirt.","She is wearing a green dress.","They are wearing black trousers.","What are you wearing?"),"common_mistakes":("a shirt blue → a blue shirt","She wearing a dress. → She is wearing a dress.","He are wearing shoes. → He is wearing shoes."),"tips":("Use is with he/she and are with they.","Trousers and shoes normally use plural grammar.")},
        "grammar_checks":(C("She ___ wearing a red dress.",("is","are","am"),"is","Use is with She."),C("Choose the natural phrase.",("a blue shirt","a shirt blue","blue a shirt"),"a blue shirt","Put the colour before the noun."),C("They ___ wearing black shoes.",("are","is","am"),"are","Use are with They.")),
        "dialogue":(("Mum","Are you ready, Sami?"),("Sami","Almost. I’m wearing my blue shirt and black trousers."),("Mum","Take your green jacket too. It’s cold."),("Sami","Which shoes?"),("Mum","The brown shoes by the door.")),
        "gist":C("What is Sami doing?",("getting ready","ordering food","doing homework"),"getting ready","They discuss the clothes he needs."),"listening_checks":(C("What colour is Sami’s shirt?",("blue","green","brown"),"blue","He says blue shirt.","I’m wearing my blue shirt."),C("What should he take?",("a green jacket","a red hat","a black dress"),"a green jacket","Mum tells him to take it.","Take your green jacket too."),C("Where are the shoes?",("by the door","under the bed","on the table"),"by the door","Mum says by the door.","The brown shoes are by the door.")),
        "shadowing":("I’m wearing a blue shirt.","She is wearing a green dress.","These trousers are black.","Which shoes are yours?"),"pronunciation":("shirt /ʃɜːt/","trousers /ˈtraʊzəz/","clothes /kləʊðz/"),"role_play":(("Partner","What are you wearing?"),("You","I’m wearing …"),("Partner","Which jacket is yours?"),("You","The … jacket is mine.")),"speaking_prompts":("Describe two items you are wearing.","Describe another person in a picture."),"speaking_question":"What are you wearing today?","speaking_challenge":"Describe a complete outfit using three clothes words and two colours.","pronunciation_focus":"Final consonants","pronunciation_tip":"Keep the final sounds in shirt, dress and clothes clear.",
        "reading_title":"The school photo","reading_passage":"Today is the class photo. Amal is wearing a green dress and black shoes. Zaid has a white shirt, blue trousers and a brown jacket. Their teacher is wearing a red hat for a funny final picture.","reading_help":"مساعدة: final picture تعني الصورة الأخيرة.","reading_checks":(C("Who is wearing a green dress?",("Amal","Zaid","the teacher"),"Amal","The first clothing description is Amal’s."),C("What colour are Zaid’s trousers?",("blue","black","brown"),"blue","The passage says blue trousers."),C("What is the teacher wearing?",("a red hat","a green jacket","white shoes"),"a red hat","The final sentence names a red hat.")),"reading_types":("Who?","Find information","What?"),
        "writing_task":"Write 3–5 sentences describing two outfits.","writing_model":"I am wearing a white shirt and blue trousers. My sister is wearing a green dress. Her shoes are black.","writing_checklist":("Use am/is/are wearing.","Put colours before clothing nouns.","Check singular and plural forms."),"writing_guided":("I am wearing ___.","My ___ is ___."),"writing_semi":("Include three clothes words.","Include two colours.","Describe two people."),"writing_check":C("Choose the correct sentence.",("She is wearing a red dress.","She wearing dress red.","She are wearing a red dress."),"She is wearing a red dress.","Use is wearing and colour before noun."),"writing_similar":C("Choose the correct sentence.",("They are wearing black shoes.","They is wearing shoes black.","They wearing black shoe."),"They are wearing black shoes.","Use are with They and put black before shoes."),
        "speaking_check":C("What are you wearing?",("I’m wearing a blue shirt.","I blue shirt wearing.","She am shirt."),"I’m wearing a blue shirt.","This directly answers with am wearing."),"speaking_similar":C("Which hat is yours?",("The red hat is mine.","Mine hat red.","I is the red."),"The red hat is mine.","This clearly identifies the item."),
        "extra_game":{"id":"outfit-memory","type":"memory","title":"Outfit Memory","prompt":"Which pair makes a natural description?","choices":("blue — shirt","shirt — quickly","wearing — Monday"),"answer":"blue — shirt","reason":"Connect colours with clothing nouns."},"mission_title":"Get Ready","mission_task":"Choose clothes for a day out and explain the outfit.","mission_steps":("Name three clothing items.","Use two colours.","Say what you are wearing.","Describe another person.","Ask Which one? once."),"mission_success":("I can describe an outfit clearly.","I can use wearing with the correct form of be."),"british_note":"Use trousers in British English; pants can have a different meaning.","vocab_subskill":"clothes","grammar_subskill":"wearing","listening_subskill":"clothing-detail",
    },
    {
        "code":"A1.13","order":13,"title":"Weather & Seasons","arabic_title":"الطقس والفصول","theme":"weather-report",
        "objectives":("Describe basic weather","Name the four seasons","Choose suitable activities"),"can_do":("I can describe today’s weather.","I can name the four seasons.","I can say what I do in different weather.","I can ask about the weather."),"review_from":("A1.5","A1.11","A1.12"),
        "vocabulary":V(("sunny","مشمس","It is sunny today.","الجو مشمس اليوم.","weather","a sunny day","sun → sunny"),("rainy","ممطر","It is a rainy morning.","إنه صباح ممطر.","weather","a rainy day","rain → rainy"),("cloudy","غائم","The sky is cloudy.","السماء غائمة.","weather","cloudy weather","cloud → cloudy"),("windy","عاصف","It is windy by the sea.","الجو عاصف قرب البحر.","weather","a windy afternoon","wind → windy"),("hot","حار","Summer is hot here.","الصيف حار هنا.","temperature","very hot",""),("cold","بارد","The morning is cold.","الصباح بارد.","temperature","very cold",""),("spring","الربيع","Spring is warm and green.","الربيع دافئ وأخضر.","season","in spring",""),("summer","الصيف","We swim in summer.","نسبح في الصيف.","season","in summer",""),("autumn","الخريف","The leaves change in autumn.","تتغير الأوراق في الخريف.","season","in autumn",""),("winter","الشتاء","I wear a jacket in winter.","أرتدي سترة في الشتاء.","season","in winter","")),
        "expressions":E(("What’s the weather like?","كيف الطقس؟","What’s the weather like today?"),("It’s sunny.","الجو مشمس.","It’s sunny and warm."),("Take your jacket.","خذ سترتك.","It’s cold. Take your jacket."),("Let’s stay inside.","لنبقَ في الداخل.","It’s rainy. Let’s stay inside.")),
        "review_checks":(C("She is ___ a jacket.",("wearing","wear","wears"),"wearing","Use is plus wearing for now."),C("The picnic is ___ Friday.",("on","in","at"),"on","Use on with a day.")),
        "grammar":{"title":"It’s + weather adjective · What’s … like?","explanation_en":"Use It’s plus an adjective to describe weather. Ask What’s the weather like? Use in with seasons.","explanation_ar":"نستخدم It’s ثم صفة لوصف الطقس. نسأل What’s the weather like? ونستخدم in مع الفصول.","examples":("It’s sunny today.","What’s the weather like?","It is cold in winter.","We swim in summer."),"common_mistakes":("It sunny. → It is sunny.","What weather is? → What’s the weather like?","on winter → in winter"),"tips":("Weather is uncountable in this meaning.","Use in before a season name.")},
        "grammar_checks":(C("It ___ rainy today.",("is","are","am"),"is","Use is with It."),C("What’s the weather ___?",("like","likes","look"),"like","The fixed question is What’s the weather like?"),C("It is cold ___ winter.",("in","on","at"),"in","Use in with a season.")),
        "dialogue":(("Lina","What’s the weather like today?"),("Dad","It’s cloudy and windy this morning."),("Lina","Can we go to the park?"),("Dad","Yes, but take your jacket. It’s rainy this afternoon."),("Lina","Okay. I like cool weather.")),
        "gist":C("What are they mainly discussing?",("today’s weather","a school subject","a birthday"),"today’s weather","They discuss clouds, wind and rain."),"listening_checks":(C("What is the morning like?",("cloudy and windy","hot and sunny","cold and snowy"),"cloudy and windy","Dad uses both weather words.","It’s cloudy and windy this morning."),C("Where does Lina want to go?",("the park","school","the café"),"the park","She asks about the park.","Can we go to the park?"),C("What should Lina take?",("a jacket","a hat","an umbrella only"),"a jacket","Dad says take your jacket.","Take your jacket.")),
        "shadowing":("What’s the weather like?","It’s sunny and warm.","It is cold in winter.","Take your jacket today."),"pronunciation":("weather /ˈweðə/","windy /ˈwɪndi/","autumn /ˈɔːtəm/"),"role_play":(("Partner","What’s the weather like?"),("You","It’s …"),("Partner","What can we do?"),("You","Let’s …")),"speaking_prompts":("Describe today’s weather.","Name your favourite season."),"speaking_question":"What’s the weather like today?","speaking_challenge":"Give a short weather report and suggest one suitable activity.","pronunciation_focus":"Weather word stress","pronunciation_tip":"Stress the first syllable in weather, windy and rainy; the n in autumn is silent.",
        "reading_title":"Four seasons","reading_passage":"Spring is warm in Green Town, and the parks are colourful. Summer is hot and sunny, so families visit the beach. Autumn is cooler and sometimes windy. Winter is short, but mornings can be cold and rainy.","reading_help":"مساعدة: cooler تعني أبرد قليلًا، وcan be تعني قد يكون.","reading_checks":(C("When do families visit the beach?",("summer","winter","autumn"),"summer","The summer sentence mentions the beach."),C("Which season is sometimes windy?",("autumn","spring","summer"),"autumn","The passage says autumn is sometimes windy."),C("What are winter mornings like?",("cold and rainy","hot and sunny","warm and green"),"cold and rainy","The final sentence gives both adjectives.")),"reading_types":("When?","Which?","Find information"),
        "writing_task":"Write 3–5 sentences about weather in two seasons.","writing_model":"Summer is hot and sunny. I swim in summer. Winter is cooler. I wear a jacket on cold days.","writing_checklist":("Use It is or It’s.","Use in with seasons.","Connect weather to an activity."),"writing_guided":("It is ___ today.","In ___, it is ___."),"writing_semi":("Include two seasons.","Use three weather words.","Add one activity."),"writing_check":C("Choose the correct sentence.",("It is rainy today.","It rainy today.","It are rainy."),"It is rainy today.","Use It is plus a weather adjective."),"writing_similar":C("Choose the correct sentence.",("It is hot in summer.","It hot on summer.","It are summer hot."),"It is hot in summer.","Use is and in with summer."),
        "speaking_check":C("What’s the weather like?",("It’s cloudy.","It cloud.","Cloudy is weather what."),"It’s cloudy.","This is a natural weather answer."),"speaking_similar":C("What can we do on a sunny day?",("We can go to the park.","We can park is.","Sunny go we."),"We can go to the park.","This is a complete suggestion."),
        "extra_game":{"id":"weather-listen","type":"listen_choose","title":"Listen & Choose","prompt":"Choose the weather you hear.","choices":("windy","sunny","rainy"),"answer":"windy","spoken":"It is windy today.","reason":"Recognise a weather word in a sentence."},"mission_title":"Today’s Weather Report","mission_task":"Give a short report and help a friend choose clothes or an activity.","mission_steps":("Describe the sky.","Say if it is hot or cold.","Name the season.","Suggest one activity.","Suggest one clothing item."),"mission_success":("I can report basic weather.","I can connect weather with everyday choices."),"british_note":"Autumn is the standard British English word; American English often uses fall.","vocab_subskill":"weather","grammar_subskill":"weather-form","listening_subskill":"weather-detail",
    },
    {
        "code":"A1.14","order":14,"title":"Hobbies & Free Time","arabic_title":"الهوايات ووقت الفراغ","theme":"weekend-club",
        "objectives":("Name common hobbies","Talk about preferences","Ask about free-time activities"),"can_do":("I can name common hobbies.","I can say what I like doing.","I can ask about free time.","I can invite someone to a simple activity."),"review_from":("A1.4","A1.5","A1.9"),
        "vocabulary":V(("football","كرة القدم","I play football on Friday.","ألعب كرة القدم يوم الجمعة.","hobby","play football",""),("swimming","السباحة","Swimming is my favourite hobby.","السباحة هوايتي المفضلة.","hobby","go swimming","swim → swimming"),("cycling","ركوب الدراجة","We go cycling in the park.","نذهب لركوب الدراجات في الحديقة.","hobby","go cycling","cycle → cycling"),("drawing","الرسم","She likes drawing animals.","تحب رسم الحيوانات.","hobby","like drawing","draw → drawing"),("music","الموسيقى","I listen to music at home.","أستمع إلى الموسيقى في المنزل.","hobby","listen to music",""),("films","الأفلام","They watch films together.","يشاهدون الأفلام معًا.","hobby","watch films",""),("games","الألعاب","He plays board games.","يلعب ألعاب الطاولة.","hobby","play games",""),("free time","وقت الفراغ","What do you do in your free time?","ماذا تفعل في وقت فراغك؟","time","in my free time",""),("often","غالبًا","I often read after school.","غالبًا أقرأ بعد المدرسة.","frequency","often play",""),("sometimes","أحيانًا","We sometimes go cycling.","نذهب أحيانًا لركوب الدراجات.","frequency","sometimes watch","")),
        "expressions":E(("What do you do in your free time?","ماذا تفعل في وقت فراغك؟","What do you do in your free time?"),("I like …ing.","أحب ...","I like drawing."),("Would you like to join us?","هل ترغب في الانضمام إلينا؟","Would you like to join us on Friday?"),("That sounds fun.","يبدو ذلك ممتعًا.","Yes, that sounds fun.")),
        "review_checks":(C("I ___ play football after school.",("often","now","yesterday"),"often","Often describes frequency."),C("She can ___ very well.",("draw","draws","drawing"),"draw","Use the base verb after can.")),
        "grammar":{"title":"like/love + -ing · frequency review","explanation_en":"Use like or love plus an -ing form for hobbies. Put often and sometimes before the main verb.","explanation_ar":"نستخدم like أو love ثم الفعل مع ing للهوايات. يأتي often وsometimes عادة قبل الفعل الأساسي.","examples":("I like drawing.","She loves swimming.","We often play games.","Do you like cycling?"),"common_mistakes":("I like draw. → I like drawing.","She like swimming. → She likes swimming.","I play often games. → I often play games."),"tips":("Add -ing after like when naming an activity.","Use do/does to ask a present simple question.")},
        "grammar_checks":(C("I like ___ pictures.",("drawing","draw","draws"),"drawing","Use an -ing form after like."),C("She ___ swimming.",("loves","love","loving"),"loves","Use loves with She in the present simple."),C("We ___ play games after school.",("often","are","yesterday"),"often","Put often before the main verb.")),
        "dialogue":(("Noura","What do you do in your free time, Ali?"),("Ali","I often play football, and I like cycling."),("Noura","Do you like swimming?"),("Ali","Yes, I do. Would you like to go on Saturday?"),("Noura","That sounds fun.")),
        "gist":C("What are they mainly discussing?",("free-time activities","school clothes","the weather"),"free-time activities","They name hobbies and make a plan."),"listening_checks":(C("What does Ali often play?",("football","tennis","computer games"),"football","Ali says he often plays football.","I often play football."),C("What other hobby does Ali like?",("cycling","singing","cooking"),"cycling","He says he likes cycling.","I like cycling."),C("What do they plan to do?",("go swimming","watch a film","draw pictures"),"go swimming","Ali invites Noura to swim.","Would you like to go swimming on Saturday?")),
        "shadowing":("I like drawing.","She loves swimming.","What do you do in your free time?","That sounds fun."),"pronunciation":("swimming /ˈswɪmɪŋ/","cycling /ˈsaɪklɪŋ/","often /ˈɒfən/"),"role_play":(("Partner","What do you do in your free time?"),("You","I like …"),("Partner","Would you like to …?"),("You","Yes, that sounds fun. / Sorry, I can’t.")),"speaking_prompts":("Name two hobbies.","Invite a partner to one activity."),"speaking_question":"What do you like doing in your free time?","speaking_challenge":"Talk for 30 seconds about two hobbies and invite a friend to one.","pronunciation_focus":"-ing and sentence stress","pronunciation_tip":"Keep the /ɪŋ/ ending clear and stress the main hobby word.",
        "reading_title":"The Friday club","reading_passage":"Our Friday club has four groups. The sports group plays football and goes cycling. The art group likes drawing. Another group listens to music and watches short films. I love games, so I am in the board-games group.","reading_help":"مساعدة: group تعني مجموعة، وboard games تعني ألعاب الطاولة.","reading_checks":(C("Which group goes cycling?",("the sports group","the art group","the games group"),"the sports group","Cycling is listed with sports."),C("What does the art group like?",("drawing","music","football"),"drawing","The passage states drawing."),C("Why is the writer in the games group?",("The writer loves games.","The writer can’t draw.","The writer has no bike."),"The writer loves games.","The final sentence gives the reason.")),"reading_types":("Which?","What?","Why?"),
        "writing_task":"Write 3–5 sentences about your free time.","writing_model":"I like swimming and cycling. I often go cycling on Friday. My friend loves drawing. We sometimes play games together.","writing_checklist":("Use like/love plus -ing.","Use often or sometimes.","Connect two ideas with and."),"writing_guided":("I like ___.","I often ___."),"writing_semi":("Include two hobbies.","Use one frequency word.","Mention a friend."),"writing_check":C("Choose the correct sentence.",("I like drawing.","I like draw.","I drawing like."),"I like drawing.","Use like plus an -ing form."),"writing_similar":C("Choose the correct sentence.",("She loves swimming.","She love swim.","She loves swim."),"She loves swimming.","Use loves with She and an -ing form."),
        "speaking_check":C("What do you do in your free time?",("I like cycling.","I cycling am.","Free time is like."),"I like cycling.","This is a clear hobby answer."),"speaking_similar":C("Would you like to play football?",("Yes, that sounds fun.","Yes, I sounding.","Football would you."),"Yes, that sounds fun.","This is a natural response to an invitation."),
        "extra_game":{"id":"hobby-fast","type":"fast_choice","title":"Fast Choice","prompt":"Choose the correct hobby sentence.","choices":("She likes drawing.","She likes draw.","She like drawing."),"answer":"She likes drawing.","reason":"Practise like plus -ing."},"mission_title":"Plan a Free Afternoon","mission_task":"Find a shared hobby and agree on a simple plan.","mission_steps":("Name two hobbies.","Say what you like doing.","Ask your partner one question.","Make one invitation.","Respond naturally."),"mission_success":("I can discuss free-time activities.","I can make and answer a simple invitation."),"vocab_subskill":"hobbies","grammar_subskill":"like-ing","listening_subskill":"hobby-detail",
    },
    {
        "code":"A1.15","order":15,"title":"Shopping","arabic_title":"التسوق","theme":"clothes-shop",
        "objectives":("Understand simple prices","Ask for a size","Buy one item politely"),"can_do":("I can ask the price of an item.","I can understand simple prices.","I can ask for a size or colour.","I can buy an item politely."),"review_from":("A1.6","A1.11","A1.12"),
        "vocabulary":V(("price","سعر","The price is thirty riyals.","السعر ثلاثون ريالًا.","shopping","the price",""),("riyal","ريال","It costs twenty riyals.","سعره عشرون ريالًا.","money","twenty riyals",""),("pound","جنيه إسترليني","The hat is ten pounds.","سعر القبعة عشرة جنيهات.","money","ten pounds",""),("size","مقاس","What size do you need?","ما المقاس الذي تحتاجه؟","shopping","size medium",""),("small","صغير","This shirt is too small.","هذا القميص صغير جدًا.","size","a small size",""),("medium","متوسط","Do you have a medium?","هل لديكم مقاس متوسط؟","size","a medium size",""),("large","كبير","I need a large jacket.","أحتاج إلى سترة كبيرة.","size","a large size",""),("cheap","رخيص","These shoes are cheap.","هذا الحذاء رخيص.","price","quite cheap",""),("expensive","غالي","The blue dress is expensive.","الفستان الأزرق غالٍ.","price","too expensive",""),("change","الباقي","Here is your change.","تفضل الباقي.","money","your change","")),
        "expressions":E(("How much is it?","كم سعره؟","How much is this shirt?"),("How much are they?","كم سعرها؟","How much are these shoes?"),("Do you have this in …?","هل لديكم هذا بـ...؟","Do you have this in blue?"),("I’ll take it.","سآخذه.","It’s a good price. I’ll take it.")),
        "review_checks":(C("I’d like ___ blue shirt, please.",("a","an","some"),"a","Use a before blue shirt."),C("The shop opens ___ Monday.",("on","in","at"),"on","Use on with a day.")),
        "grammar":{"title":"How much is/are …? · this/these review","explanation_en":"Use How much is with one item and How much are with plural items. Use this for one nearby item and these for plural nearby items.","explanation_ar":"نستخدم How much is مع شيء واحد وHow much are مع الأشياء الجمع. نستخدم this للمفرد القريب وthese للجمع القريب.","examples":("How much is this shirt?","It’s thirty riyals.","How much are these shoes?","They’re forty pounds."),"common_mistakes":("How much are this? → How much is this?","How much is these shoes? → How much are these shoes?","It thirty riyals. → It’s thirty riyals."),"tips":("Match is with one item and are with plural items.","Prices use plural riyals or pounds after numbers above one.")},
        "grammar_checks":(C("How much ___ this hat?",("is","are","am"),"is","Use is with one hat."),C("How much ___ these shoes?",("are","is","does"),"are","Use are with plural shoes."),C("___ twenty riyals.",("It’s","They is","It are"),"It’s","Use It’s for one item’s price.")),
        "dialogue":(("Assistant","Hello. Can I help you?"),("Sara","Yes, please. Do you have this shirt in blue?"),("Assistant","Yes. What size do you need?"),("Sara","Medium, please. How much is it?"),("Assistant","It’s thirty-nine riyals."),("Sara","Great. I’ll take it.")),
        "gist":C("Where are the speakers?",("in a clothes shop","at school","in a restaurant"),"in a clothes shop","They discuss a shirt, size and price."),"listening_checks":(C("What colour does Sara want?",("blue","red","green"),"blue","Sara asks for blue.","Do you have this shirt in blue?"),C("What size does she need?",("medium","small","large"),"medium","She says medium.","Medium, please."),C("How much is the shirt?",("39 riyals","30 riyals","49 riyals"),"39 riyals","The assistant says thirty-nine riyals.","It’s thirty-nine riyals.")),
        "shadowing":("How much is this shirt?","Do you have this in blue?","Medium, please.","I’ll take it."),"pronunciation":("price /praɪs/","pound /paʊnd/","thirty /ˈθɜːti/"),"role_play":(("Assistant","Can I help you?"),("You","Do you have this in …?"),("Assistant","What size?"),("You","…, please. How much is it?")),"speaking_prompts":("Ask about a colour and size.","Ask and answer a price."),"speaking_question":"What would you like to buy?","speaking_challenge":"Complete a short shopping conversation from greeting to purchase.","pronunciation_focus":"Prices and polite rhythm","pronunciation_tip":"Say price numbers clearly and stress the item, size and final amount.",
        "reading_title":"Weekend offers","reading_passage":"The town shop has weekend offers. Blue shirts are twenty-five riyals. Black trousers are forty riyals. A green jacket is sixty riyals. Red hats are fifteen riyals. The shirts have small, medium and large sizes.","reading_help":"مساعدة: offers تعني عروضًا، وsizes تعني مقاسات.","reading_checks":(C("How much are the shirts?",("25 riyals","40 riyals","60 riyals"),"25 riyals","The second sentence gives the shirt price."),C("Which item costs 60 riyals?",("the green jacket","black trousers","red hats"),"the green jacket","The jacket price is sixty riyals."),C("Which sizes do the shirts have?",("small, medium and large","small only","medium and large only"),"small, medium and large","The final sentence lists all three.")),"reading_types":("Find information","Which?","What?"),
        "writing_task":"Write a 3–5 line shopping dialogue.","writing_model":"Assistant: Can I help you? Customer: Yes, please. Do you have this shirt in blue? Assistant: Yes. It’s thirty riyals. Customer: Great. I’ll take it.","writing_checklist":("Ask for an item or colour.","Include one price.","Use please or thank you."),"writing_guided":("Do you have ___?","How much is ___?"),"writing_semi":("Include one item.","Include one size or colour.","Finish the purchase."),"writing_check":C("Choose the correct sentence.",("How much is this jacket?","How much are this jacket?","How this jacket much?"),"How much is this jacket?","Use is with one jacket."),"writing_similar":C("Choose the correct sentence.",("How much are these shoes?","How much is these shoes?","These shoes how is?"),"How much are these shoes?","Use are with plural shoes."),
        "speaking_check":C("Can I help you?",("Yes, please. I need a shirt.","Shirt help yes.","I am a shirt."),"Yes, please. I need a shirt.","This is a clear polite request."),"speaking_similar":C("The shirt is thirty riyals.",("Great. I’ll take it.","Thirty shirt am.","Take you it."),"Great. I’ll take it.","This naturally accepts the price."),
        "extra_game":{"id":"price-speed","type":"fast_choice","title":"Price Speed Round","prompt":"Choose the correct price question.","choices":("How much are these trousers?","How much is these trousers?","How are much trousers?"),"answer":"How much are these trousers?","reason":"Match are with a plural item."},"mission_title":"Buy an Outfit","mission_task":"Ask for an item, choose a colour and size, check the price and buy it.","mission_steps":("Greet the assistant.","Ask for one item.","Choose a colour or size.","Ask the price.","Accept or decline politely."),"mission_success":("I can manage a basic shop conversation.","I can understand and say a simple price."),"british_note":"Pound is the British currency word; this Saudi course also practises riyal for local use.","vocab_subskill":"shopping","grammar_subskill":"how-much","listening_subskill":"shopping-detail",
    },
    {
        "code":"A1.16","order":16,"title":"School Life","arabic_title":"الحياة المدرسية","theme":"school-day",
        "objectives":("Name school subjects","Read a simple timetable","Talk about school possessions"),"can_do":("I can name common school subjects.","I can read a simple timetable.","I can say what my class has got.","I can ask about the next lesson."),"review_from":("A1.4","A1.11","A1.14"),
        "vocabulary":V(("maths","الرياضيات","We have got maths on Monday.","لدينا رياضيات يوم الاثنين.","subject","maths lesson",""),("English","اللغة الإنجليزية","English is my favourite subject.","الإنجليزية مادتي المفضلة.","subject","English class",""),("science","العلوم","Our science lesson starts at ten.","تبدأ حصة العلوم الساعة العاشرة.","subject","science lesson",""),("art","الفن","We draw pictures in art.","نرسم صورًا في الفن.","subject","art class",""),("lesson","حصة","The lesson is forty minutes.","مدة الحصة أربعون دقيقة.","school","next lesson",""),("timetable","جدول دراسي","Check the timetable for Tuesday.","راجع الجدول ليوم الثلاثاء.","school","school timetable",""),("break","استراحة","We have a break at eleven.","لدينا استراحة الساعة الحادية عشرة.","school","lunch break",""),("classroom","فصل دراسي","Our classroom has got twenty desks.","في فصلنا عشرون مكتبًا.","school","in the classroom",""),("project","مشروع","Our science project is ready.","مشروع العلوم جاهز.","school","school project",""),("uniform","زي مدرسي","My school uniform is blue.","زيي المدرسي أزرق.","school","school uniform","")),
        "expressions":E(("What have we got next?","ما الحصة التالية؟","What have we got next?"),("We’ve got …","لدينا ...","We’ve got science next."),("What’s your favourite subject?","ما مادتك المفضلة؟","What’s your favourite subject?"),("See you after class.","أراك بعد الحصة.","See you after class.")),
        "review_checks":(C("Science is ___ Tuesday.",("on","in","at"),"on","Use on with a day."),C("I ___ drawing pictures.",("like","am","can to"),"like","Like introduces a preference.")),
        "grammar":{"title":"have got / has got","explanation_en":"Use have got with I, you, we and they. Use has got with he, she and it.","explanation_ar":"نستخدم have got مع I وyou وwe وthey، ونستخدم has got مع he وshe وit.","examples":("We have got maths today.","She has got an art project.","Have you got English next?","Yes, we have."),"common_mistakes":("She have got science. → She has got science.","We has got art. → We have got art.","Have she got maths? → Has she got maths?"),"tips":("We’ve got is the short form of We have got.","Use has with he, she and it.")},
        "grammar_checks":(C("We ___ maths today.",("have got","has got","got has"),"have got","Use have got with We."),C("She ___ an art project.",("has got","have got","is got"),"has got","Use has got with She."),C("___ you got English next?",("Have","Has","Are"),"Have","Start the question with Have for you.")),
        "dialogue":(("Adam","What have we got first today?"),("Leen","We’ve got maths at eight thirty."),("Adam","And after the break?"),("Leen","Science at eleven. We have got a project."),("Adam","Great. Science is my favourite subject.")),
        "gist":C("What are they checking?",("a school timetable","a shopping list","a weather report"),"a school timetable","They discuss subjects and lesson times."),"listening_checks":(C("What is the first lesson?",("maths","science","art"),"maths","Maths is first.","We have got maths first today."),C("What time is maths?",("8:30","9:30","11:00"),"8:30","The time is eight thirty.","Maths is at eight thirty."),C("What have they got for science?",("a project","a test","a uniform"),"a project","Leen names a project.","We have got a science project.")),
        "shadowing":("What have we got next?","We’ve got science.","She has got an art project.","See you after class."),"pronunciation":("maths /mæθs/","science /ˈsaɪəns/","timetable /ˈtaɪmteɪbəl/"),"role_play":(("Partner","What have we got next?"),("You","We’ve got …"),("Partner","What time is it?"),("You","It’s at …")),"speaking_prompts":("Name three subjects.","Describe one school day."),"speaking_question":"What is your favourite subject?","speaking_challenge":"Use a timetable to explain three lessons in order.","pronunciation_focus":"School-word stress","pronunciation_tip":"Stress the first syllable in timetable and classroom.",
        "reading_title":"Mariam’s Tuesday","reading_passage":"Mariam has got English at eight o’clock and maths at nine. The morning break is at ten. After the break, her class has got science. In the afternoon, she has got art and works on a project.","reading_help":"مساعدة: after the break تعني بعد الاستراحة.","reading_checks":(C("What is Mariam’s first lesson?",("English","maths","science"),"English","English is at eight."),C("When is the break?",("at ten","at nine","in the afternoon"),"at ten","The passage gives ten."),C("What does she do in art?",("works on a project","plays football","buys a uniform"),"works on a project","The final sentence gives the activity.")),"reading_types":("What?","When?","Find information"),
        "writing_task":"Write 3–5 sentences about a school day.","writing_model":"We have got English first. Maths is at nine o’clock. We have got a break at ten. Science is my favourite subject.","writing_checklist":("Use have got correctly.","Include two subjects.","Include one day or time."),"writing_guided":("We have got ___ on ___.","My favourite subject is ___."),"writing_semi":("Include three lessons.","Give one time.","Name a favourite subject."),"writing_check":C("Choose the correct sentence.",("We have got science today.","We has got science today.","We got have science."),"We have got science today.","Use have got with We."),"writing_similar":C("Choose the correct sentence.",("She has got art next.","She have got art next.","She got has art."),"She has got art next.","Use has got with She."),
        "speaking_check":C("What have we got next?",("We’ve got maths.","We has maths got.","Next got we."),"We’ve got maths.","This is a natural timetable answer."),"speaking_similar":C("What’s your favourite subject?",("My favourite subject is art.","Favourite art my.","I subject art."),"My favourite subject is art.","This is a complete preference answer."),
        "extra_game":{"id":"timetable-detective","type":"grammar_detective","title":"Timetable Detective","prompt":"Choose the correct timetable sentence.","choices":("She has got science at ten.","She have got science at ten.","She got science has at ten."),"answer":"She has got science at ten.","reason":"Match has got with She."},"mission_title":"Build an Ideal School Day","mission_task":"Create a simple timetable and explain it to a partner.","mission_steps":("Choose three subjects.","Give a day.","Add lesson times.","Include a break.","Explain your favourite subject."),"mission_success":("I can read and describe a timetable.","I can use have got for school life."),"british_note":"Maths is standard British English; American English usually says math.","vocab_subskill":"school","grammar_subskill":"have-got","listening_subskill":"timetable-detail",
    },
    {
        "code":"A1.17","order":17,"title":"People & Jobs","arabic_title":"الأشخاص والوظائف","theme":"people-at-work",
        "objectives":("Name common jobs","Describe people simply","Ask what someone does"),"can_do":("I can name common jobs.","I can ask what someone does.","I can describe a person simply.","I can introduce a community worker."),"review_from":("A1.2","A1.3","A1.16"),
        "vocabulary":V(("teacher","معلم","My teacher is friendly.","معلمي ودود.","job","school teacher","teach → teacher"),("doctor","طبيب","The doctor works at a hospital.","يعمل الطبيب في مستشفى.","job","family doctor",""),("nurse","ممرض","The nurse helps patients.","يساعد الممرض المرضى.","job","hospital nurse",""),("engineer","مهندس","Sara is an engineer.","سارة مهندسة.","job","an engineer",""),("driver","سائق","The bus driver starts early.","يبدأ سائق الحافلة مبكرًا.","job","bus driver","drive → driver"),("chef","طاهٍ","The chef works in a restaurant.","يعمل الطاهي في مطعم.","job","restaurant chef",""),("police officer","ضابط شرطة","A police officer helps the community.","يساعد ضابط الشرطة المجتمع.","job","police officer",""),("friendly","ودود","Our new neighbour is friendly.","جارنا الجديد ودود.","description","very friendly","friend → friendly"),("tall","طويل","The tall man is my uncle.","الرجل الطويل عمي.","description","tall person",""),("short","قصير","He has got short hair.","لديه شعر قصير.","description","short hair","")),
        "expressions":E(("What do you do?","ما عملك؟","What do you do?"),("I’m a …","أنا ...","I’m a teacher."),("What does she do?","ما عملها؟","What does she do?"),("She works at …","هي تعمل في ...","She works at a hospital.")),
        "review_checks":(C("This is ___ uncle.",("my","me","I"),"my","Use my before a family noun."),C("She ___ got a school project.",("has","have","is"),"has","Use has got with She.")),
        "grammar":{"title":"be + a/an job · simple descriptions","explanation_en":"Use be plus a or an before one job. Use is plus an adjective, or has got plus a physical feature.","explanation_ar":"نستخدم be ثم a أو an قبل الوظيفة المفردة. ونستخدم is مع الصفة، أو has got مع صفة جسدية.","examples":("He is a doctor.","She is an engineer.","Our teacher is friendly.","He has got short hair."),"common_mistakes":("She is engineer. → She is an engineer.","He are a chef. → He is a chef.","She has friendly. → She is friendly."),"tips":("Use an before a vowel sound: an engineer.","Jobs describe work, not gender or personality.")},
        "grammar_checks":(C("She is ___ engineer.",("an","a","the an"),"an","Engineer begins with a vowel sound."),C("He ___ a chef.",("is","are","has"),"is","Use is with He before a job."),C("Our teacher ___ friendly.",("is","has","are"),"is","Use is before an adjective.")),
        "dialogue":(("Rana","Who is that woman?"),("Fahad","That’s my aunt, Huda."),("Rana","What does she do?"),("Fahad","She’s an engineer. She works near the hospital."),("Rana","She looks friendly."),("Fahad","She is. She helps with community projects too.")),
        "gist":C("Who are they talking about?",("Fahad’s aunt","Rana’s teacher","a bus driver"),"Fahad’s aunt","Fahad identifies his aunt."),"listening_checks":(C("What is Huda’s job?",("engineer","doctor","teacher"),"engineer","Fahad says engineer.","Huda is an engineer."),C("Where does she work?",("near the hospital","at the school","in a restaurant"),"near the hospital","The location is stated.","She works near the hospital."),C("How does Rana describe her?",("friendly","short","tired"),"friendly","Rana uses friendly.","She looks friendly.")),
        "shadowing":("What does she do?","She’s an engineer.","Our teacher is friendly.","He has got short hair."),"pronunciation":("teacher /ˈtiːtʃə/","engineer /ˌendʒɪˈnɪə/","police /pəˈliːs/"),"role_play":(("Partner","What does this person do?"),("You","They’re a/an …"),("Partner","What are they like?"),("You","They’re …")),"speaking_prompts":("Name three jobs.","Describe one person respectfully."),"speaking_question":"What job would you like to learn about?","speaking_challenge":"Introduce a community worker with a job, workplace and positive quality.","pronunciation_focus":"Job-word stress","pronunciation_tip":"Stress the final syllable in engineer and the second syllable in police.",
        "reading_title":"People in our street","reading_passage":"Four people on our street start work early. Mr Ali is a bus driver. Amal is a nurse at the town hospital. Her brother is a chef in a small restaurant. Their neighbour, Reem, is an English teacher. They all help the community in different ways.","reading_help":"مساعدة: in different ways تعني بطرق مختلفة.","reading_checks":(C("What does Mr Ali do?",("He is a bus driver.","He is a chef.","He is a teacher."),"He is a bus driver.","The second sentence gives his job."),C("Where does Amal work?",("at the hospital","at a restaurant","at a school"),"at the hospital","The passage names the hospital."),C("Who is a teacher?",("Reem","Amal","Mr Ali"),"Reem","The final job sentence names Reem.")),"reading_types":("What?","Where?","Who?"),
        "writing_task":"Write 3–5 respectful sentences about a person and their work.","writing_model":"My aunt is a nurse. She works at a hospital. She is friendly and helpful. She has got short hair.","writing_checklist":("Use a/an before a job.","Use is before an adjective.","Avoid stereotypes."),"writing_guided":("___ is a/an ___.","He/She works at ___."),"writing_semi":("Name a job.","Give a workplace.","Add one positive quality."),"writing_check":C("Choose the correct sentence.",("She is an engineer.","She is engineer.","She an engineer is."),"She is an engineer.","Use an before engineer."),"writing_similar":C("Choose the correct sentence.",("He is a doctor.","He doctor is a.","He is an doctor."),"He is a doctor.","Use a before doctor."),
        "speaking_check":C("What does she do?",("She’s a teacher.","She teacher do.","A teacher she do."),"She’s a teacher.","This is a natural job answer."),"speaking_similar":C("What is he like?",("He’s friendly.","He has friendly.","Friendly he got."),"He’s friendly.","Use be before a personality adjective."),
        "extra_game":{"id":"job-detective","type":"grammar_detective","title":"Job Detective","prompt":"Choose the correct description.","choices":("She is an engineer.","She is a engineer.","She has engineer."),"answer":"She is an engineer.","reason":"Use an before engineer."},"mission_title":"Meet a Community Helper","mission_task":"Prepare and present a short, respectful introduction to a worker.","mission_steps":("Choose a job.","Name a workplace.","Add one useful action.","Add one positive quality.","Ask your partner a job question."),"mission_success":("I can introduce a worker clearly.","I can describe people without stereotypes."),"vocab_subskill":"jobs","grammar_subskill":"job-description","listening_subskill":"person-detail",
    },
    {
        "code":"A1.18","order":18,"title":"Countries & Nationalities","arabic_title":"الدول والجنسيات","theme":"international-club",
        "objectives":("Name selected countries and nationalities","Say where someone is from","Say which language someone speaks"),"can_do":("I can say where I am from.","I can name selected nationalities.","I can say which language I speak.","I can ask about someone’s country."),"review_from":("A1.1","A1.11","A1.17"),
        "vocabulary":V(("Saudi Arabia","المملكة العربية السعودية","I am from Saudi Arabia.","أنا من المملكة العربية السعودية.","country","from Saudi Arabia",""),("Saudi","سعودي","Maha is Saudi.","مها سعودية.","nationality","Saudi student",""),("the United Kingdom","المملكة المتحدة","Owen is from the United Kingdom.","أوين من المملكة المتحدة.","country","the United Kingdom",""),("British","بريطاني","Our guest is British.","ضيفنا بريطاني.","nationality","British English",""),("Egypt","مصر","Nour is from Egypt.","نور من مصر.","country","from Egypt",""),("Egyptian","مصري","Her friend is Egyptian.","صديقتها مصرية.","nationality","Egyptian family",""),("India","الهند","Arun is from India.","آرون من الهند.","country","from India",""),("Indian","هندي","He is Indian.","هو هندي.","nationality","Indian student",""),("Arabic","العربية","We speak Arabic at home.","نتحدث العربية في المنزل.","language","speak Arabic",""),("English","الإنجليزية","They study English at school.","يدرسون الإنجليزية في المدرسة.","language","speak English","")),
        "expressions":E(("Where are you from?","من أين أنت؟","Where are you from?"),("I’m from …","أنا من ...","I’m from Saudi Arabia."),("What nationality are you?","ما جنسيتك؟","What nationality are you?"),("What languages do you speak?","ما اللغات التي تتحدثها؟","What languages do you speak?")),
        "review_checks":(C("My name ___ Layla.",("is","are","am"),"is","Use is with My name."),C("He is ___ doctor.",("a","an","some"),"a","Use a before doctor.")),
        "grammar":{"title":"be from · be + nationality · speak + language","explanation_en":"Use be from with a country, be with a nationality, and speak with a language.","explanation_ar":"نستخدم be from مع الدولة، وbe مع الجنسية، وspeak مع اللغة.","examples":("I am from Saudi Arabia.","She is Egyptian.","He speaks Arabic and English.","Where are they from?"),"common_mistakes":("I am Saudi Arabia. → I am from Saudi Arabia.","She is from Egyptian. → She is Egyptian.","He speaks British. → He speaks English."),"tips":("Countries, nationalities and languages begin with capital letters.","Use the before United Kingdom.")},
        "grammar_checks":(C("I am ___ India.",("from","at","nationality"),"from","Use from before a country."),C("She is ___.",("Egyptian","Egypt","Arabic language"),"Egyptian","Use a nationality after is."),C("They ___ Arabic and English.",("speak","are","from"),"speak","Use speak before languages.")),
        "dialogue":(("Host","Welcome to the international club. Where are you from, Dan?"),("Dan","I’m from the United Kingdom. I’m British."),("Host","What languages do you speak?"),("Dan","English, and a little Arabic."),("Host","Great. Aisha is Saudi, and she speaks both languages too.")),
        "gist":C("Where are the speakers?",("at an international club","in a clothes shop","at a bus stop"),"at an international club","The host welcomes Dan to the club."),"listening_checks":(C("Where is Dan from?",("the United Kingdom","India","Egypt"),"the United Kingdom","Dan names the country.","I’m from the United Kingdom."),C("What is Dan’s nationality?",("British","Saudi","Egyptian"),"British","Dan says British.","I’m British."),C("Which languages does Aisha speak?",("Arabic and English","English only","Arabic and Hindi"),"Arabic and English","The host says both languages.","Aisha speaks Arabic and English.")),
        "shadowing":("Where are you from?","I’m from Saudi Arabia.","She is Egyptian.","What languages do you speak?"),"pronunciation":("British /ˈbrɪtɪʃ/","Egyptian /ɪˈdʒɪpʃən/","Arabic /ˈærəbɪk/"),"role_play":(("Partner","Where are you from?"),("You","I’m from …"),("Partner","What languages do you speak?"),("You","I speak …")),"speaking_prompts":("Say your country and nationality.","Name a language you study."),"speaking_question":"Where are you from and what languages do you speak?","speaking_challenge":"Introduce yourself to an international club in four clear sentences.","pronunciation_focus":"Country and nationality stress","pronunciation_tip":"Stress BRIT in British and GYP in Egyptian.",
        "reading_title":"Our online class","reading_passage":"Our online class has four new learners. Salma is from Saudi Arabia and speaks Arabic and English. Yusuf is Egyptian and lives in Cairo. Priya is from India and speaks Hindi and English. Jack is British and lives in Manchester. Everyone is learning together.","reading_help":"مساعدة: everyone تعني الجميع، وtogether تعني معًا.","reading_checks":(C("Who is from India?",("Priya","Salma","Jack"),"Priya","The passage links Priya and India."),C("Where does Yusuf live?",("Cairo","Manchester","Riyadh"),"Cairo","The passage names Cairo."),C("Who is British?",("Jack","Yusuf","Salma"),"Jack","The fourth learner is British.")),"reading_types":("Who?","Where?","Find information"),
        "writing_task":"Write 3–5 sentences for an international class profile.","writing_model":"My name is Salma. I am from Saudi Arabia. I am Saudi. I speak Arabic and English.","writing_checklist":("Use from before a country.","Use capital letters for names.","Separate country, nationality and language."),"writing_guided":("I am from ___.","I speak ___."),"writing_semi":("Give a name.","Give a country and nationality.","Name one or two languages."),"writing_check":C("Choose the correct sentence.",("She is from Egypt.","She is from Egyptian.","She from is Egypt."),"She is from Egypt.","Use a country after from."),"writing_similar":C("Choose the correct sentence.",("He is British.","He is Britain from.","He speaks British."),"He is British.","British is a nationality."),
        "speaking_check":C("Where are you from?",("I’m from Saudi Arabia.","I Saudi Arabia am.","I nationality Saudi."),"I’m from Saudi Arabia.","This is a natural country answer."),"speaking_similar":C("What languages do you speak?",("I speak Arabic and English.","I am Arabic speak.","Languages from English."),"I speak Arabic and English.","Use speak before languages."),
        "extra_game":{"id":"country-match","type":"word_match","title":"Country Match","prompt":"Choose the matching pair.","choices":("Egypt — Egyptian","India — British","the UK — Saudi"),"answer":"Egypt — Egyptian","reason":"Match a country with its nationality."},"mission_title":"Join an International Club","mission_task":"Exchange simple profile information respectfully with a partner.","mission_steps":("Give your name.","Say where you are from.","Give a nationality.","Name languages you speak or study.","Ask your partner one question."),"mission_success":("I can exchange basic international profile information.","I use country and nationality words respectfully."),"british_note":"Use the United Kingdom or the UK for the country; British is the nationality adjective.","vocab_subskill":"countries-nationalities","grammar_subskill":"from-nationality","listening_subskill":"profile-detail",
    },
    {
        "code":"A1.19","order":19,"title":"Everyday English","arabic_title":"الإنجليزية اليومية","theme":"getting-help",
        "objectives":("Ask for help politely","Clarify simple information","Handle short everyday exchanges"),"can_do":("I can ask for help politely.","I can ask someone to repeat or speak slowly.","I can give simple contact information.","I can handle a short everyday problem."),"review_from":("A1.6","A1.8","A1.9"),
        "vocabulary":V(("help","مساعدة","Can you help me, please?","هل يمكنك مساعدتي من فضلك؟","communication","ask for help",""),("message","رسالة","Please leave a short message.","اترك رسالة قصيرة من فضلك.","communication","leave a message",""),("phone call","مكالمة هاتفية","I have a phone call at three.","لدي مكالمة هاتفية الساعة الثالثة.","communication","make a phone call",""),("address","عنوان","What is the school address?","ما عنوان المدرسة؟","information","email address",""),("appointment","موعد","My appointment is on Tuesday.","موعدي يوم الثلاثاء.","arrangement","book an appointment",""),("repeat","يكرر","Could you repeat that, please?","هل يمكنك تكرار ذلك من فضلك؟","communication","repeat that",""),("slowly","ببطء","Please speak slowly.","تحدث ببطء من فضلك.","communication","speak slowly","slow → slowly"),("understand","يفهم","I don’t understand this word.","لا أفهم هذه الكلمة.","communication","understand clearly",""),("problem","مشكلة","There is a problem with the time.","هناك مشكلة في الوقت.","communication","small problem",""),("ready","جاهز","I’m ready now.","أنا جاهز الآن.","state","ready to start","")),
        "expressions":E(("Could you repeat that, please?","هل يمكنك تكرار ذلك من فضلك؟","Could you repeat the time, please?"),("Please speak slowly.","تحدث ببطء من فضلك.","Sorry, please speak slowly."),("I don’t understand.","أنا لا أفهم.","I’m sorry. I don’t understand."),("No problem.","لا مشكلة.","No problem. I can help.")),
        "review_checks":(C("I’d like some water, ___.",("please","slow","problem"),"please","Please makes a request polite."),C("Turn ___ at the bank.",("left","yesterday","hungry"),"left","Left completes the direction.")),
        "grammar":{"title":"Polite requests and clarification","explanation_en":"Use Can you or Could you plus a base verb for a polite request. Use Please plus a base verb for a clear instruction.","explanation_ar":"نستخدم Can you أو Could you ثم الفعل الأساسي للطلب المهذب. ونستخدم Please ثم الفعل الأساسي للتوجيه الواضح.","examples":("Could you repeat that, please?","Can you help me?","Please speak slowly.","I don’t understand."),"common_mistakes":("Could you repeating? → Could you repeat?","Please to speak slowly. → Please speak slowly.","I no understand. → I don’t understand."),"tips":("Could you is a polite everyday form.","Use a calm tone and please when asking for help.")},
        "grammar_checks":(C("Could you ___ that, please?",("repeat","repeating","repeats"),"repeat","Use the base verb after could you."),C("Please ___ slowly.",("speak","speaks","to speak"),"speak","Use the base verb after Please."),C("I ___ understand.",("don’t","am not","no"),"don’t","Use don’t before a base verb.")),
        "dialogue":(("Caller","Hello. I’d like to make an appointment, please."),("Assistant","Of course. Is Tuesday at two o’clock okay?"),("Caller","Sorry, could you repeat the time, please?"),("Assistant","Two o’clock."),("Caller","Thank you. What’s the address?"),("Assistant","It’s 18 King Street. I can send a message too.")),
        "gist":C("Why does the caller phone?",("to make an appointment","to order lunch","to discuss the weather"),"to make an appointment","The first request states the purpose."),"listening_checks":(C("Which day is the appointment?",("Tuesday","Thursday","Friday"),"Tuesday","The assistant offers Tuesday.","The appointment is on Tuesday."),C("What time is it?",("2:00","3:00","12:00"),"2:00","The time is repeated.","The appointment is at two o’clock."),C("What is the address?",("18 King Street","80 Queen Street","18 Park Road"),"18 King Street","The assistant gives the address.","The address is eighteen King Street.")),
        "shadowing":("Could you repeat that, please?","Please speak slowly.","I don’t understand.","No problem. I can help."),"pronunciation":("could /kʊd/","address /əˈdres/","appointment /əˈpɔɪntmənt/"),"role_play":(("You","I’d like to make an appointment."),("Partner","Is Tuesday at two okay?"),("You","Could you repeat …?"),("Partner","No problem.")),"speaking_prompts":("Ask for repetition.","Give a short address or appointment time."),"speaking_question":"What do you say when you do not understand?","speaking_challenge":"Solve one phone, direction or appointment problem politely.","pronunciation_focus":"Polite sentence rhythm","pronunciation_tip":"Stress the key information and keep could you unstressed and smooth.",
        "reading_title":"Three useful messages","reading_passage":"Message 1: Your doctor’s appointment is on Monday at four. Message 2: The English class is now in Room 12. Please go upstairs and turn right. Message 3: Sami called at ten. Please phone him after lunch. His number is 055 123 4567.","reading_help":"مساعدة: called تعني اتصل، وafter lunch تعني بعد الغداء.","reading_checks":(C("When is the doctor’s appointment?",("Monday at four","Tuesday at two","Friday at ten"),"Monday at four","Message 1 gives the day and time."),C("Where is the English class?",("Room 12","Room 20","downstairs"),"Room 12","Message 2 gives the room."),C("What should the reader do after lunch?",("phone Sami","visit the doctor","go upstairs"),"phone Sami","Message 3 asks for a phone call.")),"reading_types":("When?","Where?","What?"),
        "writing_task":"Write 3–5 lines for a clear everyday message.","writing_model":"Hello Sara. Your appointment is on Tuesday at two o’clock. The address is 18 King Street. Please call me if there is a problem.","writing_checklist":("State the purpose.","Include exact key information.","Use a polite request."),"writing_guided":("Your ___ is on ___ at ___.","Please ___."),"writing_semi":("Include a day and time.","Add a place or number.","Finish politely."),"writing_check":C("Choose the polite request.",("Could you repeat that, please?","You repeat now.","Repeating you?"),"Could you repeat that, please?","Could you plus a base verb is polite."),"writing_similar":C("Choose the clear message.",("Please call me at three.","Call three me please at.","Please to calling three."),"Please call me at three.","Use Please plus a base verb."),
        "speaking_check":C("The speaker is too fast. What do you say?",("Please speak slowly.","You fast no.","Slowly are speak."),"Please speak slowly.","This is a clear polite request."),"speaking_similar":C("You did not hear the time. What do you say?",("Could you repeat the time, please?","Time repeat you is.","I time no."),"Could you repeat the time, please?","This politely asks for repetition."),
        "extra_game":{"id":"conversation-choice","type":"conversation_choice","title":"Conversation Choice","prompt":"Choose the best response: ‘Sorry, I don’t understand.’","choices":("No problem. I’ll say it again.","The address is a job.","Yesterday is slowly."),"answer":"No problem. I’ll say it again.","reason":"Choose a helpful, natural response."},"mission_title":"Solve Three Everyday Problems","mission_task":"Complete three mini-situations: ask for repetition, confirm an appointment and leave a message.","mission_steps":("Ask for help politely.","Clarify one detail.","Repeat the correct information.","Write a short message.","Confirm the problem is solved."),"mission_success":("I can repair a simple conversation.","I can exchange essential everyday information."),"british_note":"Could you…? is a common polite request in British English; address is stressed on the second syllable as a noun.","vocab_subskill":"everyday-communication","grammar_subskill":"polite-requests","listening_subskill":"message-detail",
    },
    {
        "code":"A1.20","order":20,"title":"A1 Real-Life Challenge","arabic_title":"تحدي A1 للحياة الواقعية","theme":"community-day-challenge",
        "objectives":("Combine core A1 language","Complete connected real-life tasks","Prepare for the separate A1 Final"),"can_do":("I can introduce myself and exchange personal information.","I can understand key details in a simple conversation.","I can solve familiar everyday tasks.","I can create a short spoken and written response."),"review_from":("A1.11","A1.15","A1.18","A1.19"),
        "vocabulary":V(("name","اسم","Write your name on the form.","اكتب اسمك في النموذج.","review","full name",""),("date","تاريخ","Check the event date.","تحقق من تاريخ الفعالية.","review","event date",""),("weather","طقس","The weather is warm today.","الطقس دافئ اليوم.","review","weather report",""),("clothes","ملابس","Take suitable clothes for the trip.","خذ ملابس مناسبة للرحلة.","review","suitable clothes",""),("hobby","هواية","Football is his favourite hobby.","كرة القدم هوايته المفضلة.","review","favourite hobby",""),("price","سعر","Ask about the ticket price.","اسأل عن سعر التذكرة.","review","ticket price",""),("job","وظيفة","Her job is in a school.","وظيفتها في مدرسة.","review","ask about a job",""),("country","دولة","Say which country you are from.","اذكر الدولة التي أنت منها.","review","home country",""),("help","مساعدة","Ask for help when needed.","اطلب المساعدة عند الحاجة.","review","get help",""),("plan","خطة","Our plan has four steps.","خطتنا لها أربع خطوات.","challenge","make a plan","")),
        "expressions":E(("Let’s check the plan.","لنتحقق من الخطة.","Let’s check the plan first."),("What do we need?","ماذا نحتاج؟","What do we need for the day?"),("Could you help me?","هل يمكنك مساعدتي؟","Could you help me with this form?"),("We’re ready!","نحن جاهزون!","Everything is correct. We’re ready!")),
        "review_checks":(C("The event is ___ Saturday.",("on","in","at"),"on","Use on with a day."),C("How much ___ these tickets?",("are","is","does"),"are","Use are with plural tickets.")),
        "grammar":{"title":"Integrated A1 language review — no new grammar","explanation_en":"Choose familiar A1 forms for identity, time, place, needs, preferences, prices and polite requests. This unit introduces no new grammar.","explanation_ar":"اختر صيغ A1 المألوفة للهوية والوقت والمكان والاحتياجات والتفضيلات والأسعار والطلبات المهذبة. لا تقدم هذه الوحدة قاعدة جديدة.","examples":("I’m from Saudi Arabia and I speak Arabic and English.","The event is on Saturday at ten.","How much are the tickets?","Could you repeat the address, please?"),"common_mistakes":("The event in Saturday. → The event is on Saturday.","How much is the tickets? → How much are the tickets?","Could you repeating? → Could you repeat?"),"tips":("Read the whole situation before choosing a form.","Check subject, time word and singular or plural.")},
        "grammar_checks":(C("The meeting ___ at ten.",("is","are","has"),"is","Use is with one meeting."),C("She ___ from Egypt.",("is","are","speaks"),"is","Use be from with a country."),C("Could you ___ me, please?",("help","helps","helping"),"help","Use the base verb after could you.")),
        "dialogue":(("Guide","Welcome to Community Day. Can I have your name, please?"),("Visitor","I’m Amal. I’m from Saudi Arabia."),("Guide","Great. The art activity is at ten, and the sports activity is at eleven thirty."),("Visitor","Could you repeat the sports time, please?"),("Guide","Eleven thirty. Tickets are fifteen riyals."),("Visitor","Thanks. I’ll take one ticket for the art activity.")),
        "gist":C("What is the visitor doing?",("joining a community event","buying school clothes","calling a doctor"),"joining a community event","The exchange covers registration and an activity ticket."),"listening_checks":(C("What is the visitor’s name?",("Amal","Sara","Mariam"),"Amal","She introduces herself.","My name is Amal."),C("What time is the sports activity?",("11:30","10:00","12:30"),"11:30","The guide repeats eleven thirty.","The sports activity is at eleven thirty."),C("How much is one ticket?",("15 riyals","50 riyals","30 riyals"),"15 riyals","The guide gives the price.","One ticket is fifteen riyals.")),
        "shadowing":("Can I have your name, please?","The activity is at eleven thirty.","Could you repeat that, please?","I’ll take one ticket."),"pronunciation":("community /kəˈmjuːnəti/","activity /ækˈtɪvəti/","fifteen /ˌfɪfˈtiːn/"),"role_play":(("Guide","Can I have your name?"),("You","I’m … and I’m from …"),("Guide","Which activity would you like?"),("You","I’d like … How much is it?")),"speaking_prompts":("Introduce yourself for an event.","Ask for one activity, time and price."),"speaking_question":"How would you join a new community activity?","speaking_challenge":"Complete a two-minute role-play: register, choose an activity, clarify one detail and close politely.","pronunciation_focus":"Key-information stress","pronunciation_tip":"Stress names, dates, times and prices so your listener can follow the plan.",
        "reading_title":"Community Day programme","reading_passage":"Community Day is on Saturday, 22 June, at Green Park. Registration opens at nine thirty. Art starts at ten and football starts at eleven thirty. A family lunch is at one o’clock. Tickets are fifteen riyals. Wear a hat because the weather is sunny and warm. Ask at the blue help desk if you have a problem.","reading_help":"مساعدة: registration تعني التسجيل، وhelp desk تعني مكتب المساعدة.","reading_checks":(C("When does registration open?",("9:30","10:00","11:30"),"9:30","The second sentence gives the time."),C("What should visitors wear?",("a hat","a uniform","a warm jacket"),"a hat","The weather advice names a hat."),C("Where can visitors get help?",("at the blue help desk","at the football field","at lunch"),"at the blue help desk","The last sentence gives the place.")),"reading_types":("When?","What?","Where?"),
        "writing_task":"Complete an event plan and write 4–6 connected sentences about your visit.","writing_model":"My name is Amal and I am from Saudi Arabia. I want to join the art activity on Saturday. It starts at ten o’clock. One ticket is fifteen riyals. I need a hat because it is sunny.","writing_checklist":("Introduce yourself.","Include a day, time and activity.","Add a price or practical need.","Check capitals and full stops."),"writing_guided":("My name is ___ and I am from ___.","I want to join ___ at ___."),"writing_semi":("Add an activity and time.","Add a price.","Give one weather or clothing decision."),"writing_check":C("Choose the clearest event plan.",("I’ll join art at ten on Saturday.","I join at art Saturday ten on.","Art ten Saturday am."),"I’ll join art at ten on Saturday.","The sentence gives activity, time and day clearly."),"writing_similar":C("Choose the clearest practical sentence.",("I need a hat because it is sunny.","Hat because sunny needing I.","It hat is need."),"I need a hat because it is sunny.","This links a need to the weather."),
        "speaking_check":C("You did not hear the activity time. What do you say?",("Could you repeat the time, please?","Time you repeat is.","I time no."),"Could you repeat the time, please?","This repairs the conversation politely."),"speaking_similar":C("The ticket price is acceptable. What do you say?",("Great. I’ll take one, please.","One take great I.","Ticket am please."),"Great. I’ll take one, please.","This closes the purchase naturally."),
        "extra_game":{"id":"a1-escape-room","type":"escape_room","title":"A1 Unit Escape Room","prompt":"The event is Saturday, the ticket is £15 and you need one. Choose the useful sentence.","choices":("I’ll take one ticket for Saturday, please.","Tickets Saturday one am.","Could weather job fifteen?"),"answer":"I’ll take one ticket for Saturday, please.","reason":"Integrate date, quantity and a polite purchase."},"mission_title":"Community Day Real-Life Challenge","mission_task":"Complete one connected scenario using listening, speaking, reading and writing; this prepares you for, but does not replace, the separate A1 Final.","mission_steps":("Read the programme and choose an activity.","Listen and record the correct time and price.","Register with basic personal information.","Ask one clarification question.","Write your final visit plan.","Perform the complete role-play."),"mission_success":("I can combine core A1 skills in one scenario.","I can recover when I miss information.","I am ready to attempt the separate A1 readiness review."),"british_note":"The challenge follows British date order and en-GB audio preference; £ is read as pounds.","vocab_subskill":"integrated-review","grammar_subskill":"integrated-a1","listening_subskill":"integrated-detail",
    },
)


EXPANDED_A1_UNITS = tuple(build_unit(spec) for spec in SPECS)
