"""Authored A2 curriculum data used by the shared data-driven unit engine."""

from english_path.services.units.a2_factory import game, question as q, unit, word as w
from english_path.services.units.factory import activity_question as aq


SPECS = {
    2: {
        "title": "What Happened?", "ar": "ماذا حدث؟", "theme": "past-events",
        "words": (("event","حدث"),("arrive","يصل"),("leave","يغادر"),("happen","يحدث"),("suddenly","فجأة"),("yesterday","أمس"),("last weekend","نهاية الأسبوع الماضية"),("miss","يفوّت"),("invite","يدعو"),("enjoy","يستمتع")),
        "grammar": ("Past Simple in stories", "Past Simple places completed actions in a finished past time.", "Use it to report events in order, with yesterday, ago, or last…", "subject + past verb; did not + base verb; Did + subject + base verb?", ("We arrived at eight.","She didn't miss the bus.","Did you enjoy the event?"), ("Did you went? → Did you go?","I didn't arrived → I didn't arrive","We visit yesterday → We visited yesterday"), "Past Simple answers what happened at a finished time.", "Did they leave early? — Yes, they did."),
        "dialogue": (("Mona","How was your weekend?"),("Huda","Busy! I visited my aunt on Friday. On Saturday, we went to a school event."),("Mona","What happened there?"),("Huda","The lights suddenly went out, but they came back after five minutes. Everyone laughed.")),
        "audio": "Huda visited her aunt on Friday. On Saturday she went to a school event. The lights went out for five minutes, then everyone laughed.",
        "read": ("A surprising Saturday", "Last Saturday, Sami planned to meet his friend at the sports centre. He left home at nine, but the bus arrived late. When he reached the centre, his friend was not there. Sami called him and discovered that they had chosen different entrances. They finally met at half past ten, played basketball, and laughed about the mistake."),
        "writing": ("Write 6–8 sentences about your last weekend.", "Last weekend was busy. On Friday, I visited my cousins and we cooked lunch. On Saturday, I studied in the morning, then I played football. I felt tired, but I enjoyed the day.", ("Last weekend…","First…","Then…","Finally…")),
        "mission": "Tell a friend what happened yesterday in a clear order.", "review": ("A1.10 basic Past Simple","A1.4 time expressions"), "support": "clear-toggle",
        "mcq": (("vocabulary","time-markers","The phrase for the previous Saturday and Sunday is ___.",("last weekend","next weekend","every weekend"),"last weekend"),("vocabulary","events","The concert is an important school ___.",("event","arrival","invitation"),"event"),("grammar","irregular-past","We ___ to the event yesterday.",("went","go","did went"),"went"),("grammar","past-negative","She ___ the bus.",("didn't miss","didn't missed","not miss"),"didn't miss"),("grammar","past-question","___ you enjoy the match?",("Did","Were","Do"),"Did"),("listening","sequence","What did Huda do on Friday?",("visited her aunt","went to school","played basketball"),"visited her aunt"),("listening","detail","How long were the lights out?",("five minutes","ten minutes","one hour"),"five minutes"),("reading","inference","Why did Sami and his friend meet late?",("They waited at different entrances.","They forgot the day.","The centre was closed."),"They waited at different entrances."),("writing","sequence","Choose the clearest story order.",("First we arrived. Then the game began.","Then first the game arrived.","We began because first."),"First we arrived. Then the game began."),("speaking","past-response","What did you do yesterday?",("I studied at home.","I study tomorrow.","I am yesterday."),"I studied at home.")),
    },
    3: {
        "title":"Life Experiences","ar":"تجارب الحياة","theme":"experiences",
        "words":(("experience","تجربة"),("abroad","في الخارج"),("visit","يزور"),("try","يجرّب"),("ride","يركب"),("climb","يتسلّق"),("ever","سبق أن"),("never","أبدًا"),("already","بالفعل"),("yet","بعد")),
        "grammar":("Present Perfect: experiences","Present Perfect connects a past experience to now without naming a finished time.","Use have/has + past participle with ever, never, already, just, and yet.","I/you/we/they have + participle; he/she has + participle",("I have visited Jeddah.","Has she ever ridden a horse?","They haven't finished yet."),("I have went → I have gone","She have tried → She has tried","I have visited last year → I visited last year"),"Present Perfect: no finished time; Past Simple: a finished time such as last year.","Have you ever travelled abroad?"),
        "dialogue":(("Rami","Have you ever travelled abroad?"),("Lina","Yes, I've visited Bahrain twice."),("Rami","When did you last go?"),("Lina","I went last summer. I've never travelled alone, though.")),
        "audio":"Lina has visited Bahrain twice. She last went in the summer. She has never travelled alone.",
        "read":("Three new experiences","This year, Amal has tried three new activities. She has already completed a cooking course and has just learned to ride a horse. She has not climbed a mountain yet, but she plans to try next month. Last Thursday, she cooked a new dish for her family. Everyone enjoyed it, so Amal wants to practise again."),
        "writing":("Write about three experiences you have or have never had.","I have visited two cities outside my region. I have already tried camping, but I have never climbed a mountain. Last year, I camped with my family near Taif.",( "I have already…","I have never…","Last year, I…")),
        "mission":"Interview a partner about life experiences and ask one past-time follow-up.","review":("A1.10 Past Simple","A1.9 question forms"),"support":"clear-toggle",
        "mcq":(("vocabulary","experience","Something you do or that happens to you is an ___.",("experience","account","schedule"),"experience"),("vocabulary","travel","If you travel to another country, you travel ___.",("abroad","already","yet"),"abroad"),("grammar","present-perfect-form","She ___ tried skiing.",("has","have","did"),"has"),("grammar","ever-question","___ you ever ridden a horse?",("Have","Did","Has"),"Have"),("grammar","past-vs-perfect","I ___ Jeddah last year.",("visited","have visited","visit ever"),"visited"),("listening","detail","How many times has Lina visited Bahrain?",("twice","once","never"),"twice"),("listening","finished-time","When did Lina last go?",("last summer","this morning","next year"),"last summer"),("reading","sequence","What has Amal just learned?",("to ride a horse","to climb a mountain","to drive"),"to ride a horse"),("reading","inference","Why does Amal want to cook again?",("Her family enjoyed the dish.","The course was cancelled.","She dislikes camping."),"Her family enjoyed the dish."),("speaking","follow-up","Choose the useful follow-up after 'Yes, I have.'",("When did you do it?","Do you yesterday?","Have when it?"),"When did you do it?")),
    },
    4: {
        "title":"Plans & Dreams","ar":"الخطط والأحلام","theme":"future-plans",
        "words":(("goal","هدف"),("plan","خطة"),("career","مسار مهني"),("degree","درجة علمية"),("apply","يتقدم"),("save","يدّخر"),("hope","يأمل"),("future","المستقبل"),("prediction","توقع"),("decision","قرار")),
        "grammar":("Going to and will","Both forms talk about the future, but the speaker's reason changes the choice.","Use going to for prior plans/evidence; will for instant decisions and general predictions.","am/is/are going to + base verb; will + base verb",("I'm going to study engineering.","Those clouds are dark. It is going to rain.","I'll answer the phone."),("I going to study → I'm going to study","I will to help → I will help","Look! It will fall → It is going to fall"),"going to = plan/evidence; will = decision now/prediction.","The doorbell is ringing. I'll open the door."),
        "dialogue":(("Salem","What are you going to do after school?"),("Yara","I'm going to apply for a design course. I've already prepared my work."),("Salem","That sounds great. I think you'll enjoy it."),("Yara","Thanks! Oh, the application closes today. I'll send it now.")),
        "audio":"Yara plans to apply for a design course and has prepared her work. The application closes today, so she decides to send it now.",
        "read":("A plan for next year","Dear Noor, next year I am going to finish my language course and apply for a summer job. I want to save money for a short trip. I think the job will teach me useful skills, but I know it may be challenging. This month, I am going to update my CV and ask my teacher for advice."),
        "writing":("Write an email about your plans for next year.","Next year, I am going to improve my English and join a sports club. I will probably be busy, so I am going to make a weekly plan. I hope these goals will help me feel more confident.",( "Next year, I'm going to…","I think … will…","I hope…")),
        "mission":"Create a future plan with two intentions, one prediction, and a first step.","review":("A1.5 actions now","A1.9 can for ability"),"support":"optional",
        "mcq":(("vocabulary","goals","Something you want to achieve is a ___.",("goal","degree","prediction"),"goal"),("vocabulary","education","You ___ for a course by sending a form.",("apply","save","hope"),"apply"),("grammar","prior-plan","I bought paint because I ___ decorate my room.",("am going to","will instantly","was"),"am going to"),("grammar","instant-decision","The phone is ringing. I ___ answer it.",("will","am going to yesterday","did"),"will"),("grammar","evidence","Look at those clouds! It ___.",("is going to rain","will to rain","rained"),"is going to rain"),("listening","speaker-intention","Why will Yara send the application now?",("It closes today.","The course ended.","Salem sent it."),"It closes today."),("listening","detail","What course does Yara want?",("design","medicine","cooking"),"design"),("reading","purpose","Why does the writer want a summer job?",("to save money and learn skills","to leave school","to cancel a trip"),"to save money and learn skills"),("writing","cohesion","Choose the best plan sentence.",("I am going to update my CV this month.","I going update yesterday.","I will to updated."),"I am going to update my CV this month."),("speaking","prediction","Choose a prediction.",("I think the course will be useful.","I applied last week.","I am studying now."),"I think the course will be useful.")),
    },
    5: {
        "title":"Health & Advice","ar":"الصحة والنصيحة","theme":"health-language",
        "words":(("headache","صداع"),("fever","حمّى"),("tired","متعب"),("medicine","دواء"),("doctor","طبيب"),("rest","راحة"),("exercise","تمرين"),("healthy","صحي"),("sick","مريض"),("pain","ألم")),
        "grammar":("Advice, rules, and necessity","Modal choices show whether something is advice, a rule, or necessary.","Use should for advice, must/mustn't for strong rules, and have to/don't have to for external necessity.","should/must + base verb; have/has to + base verb",("You should rest.","Visitors must wash their hands.","You don't have to come early."),("You should to rest → You should rest","He have to go → He has to go","You mustn't pay = payment is forbidden, not unnecessary"),"should = recommendation; mustn't = prohibited; don't have to = not necessary.","You have a headache. What should you do?"),
        "dialogue":(("Patient","I have a headache and I feel tired."),("Doctor","You should rest and drink water. Do you have a fever?"),("Patient","No, I don't."),("Doctor","You don't have to take medicine now, but you must call for help if you feel much worse.")),
        "audio":"A patient feels tired and has a headache but no fever. The doctor suggests rest and water and explains when the patient must get help.",
        "read":("Language for a healthy week","Our class created a general wellness poster. It says students should sleep enough and take regular breaks from screens. During sports, everyone must follow the safety rules. Students do not have to exercise in the same way: walking, swimming, and team games are all options. The poster teaches English for discussing habits; it is not personal medical advice."),
        "writing":("Write a friendly message giving general wellness advice.","Hi Sami, I'm sorry you feel tired. You should rest and drink some water. You shouldn't stay up late tonight. If you feel much worse, you must tell an adult.",( "You should…","You shouldn't…","You don't have to…")),
        "mission":"Complete a doctor–patient role-play using advice and obligation language.","review":("A1.6 food and drinks","A1.9 can/can't"),"support":"optional",
        "mcq":(("vocabulary","symptoms","A high body temperature is a ___.",("fever","rest","doctor"),"fever"),("vocabulary","wellness","Sleep and movement can be part of a ___ routine.",("healthy","sick","pain"),"healthy"),("grammar","advice","You feel tired. You ___ rest.",("should","mustn't","don't"),"should"),("grammar","prohibition","You ___ enter this staff-only room.",("mustn't","don't have to","should"),"mustn't"),("grammar","not-necessary","The visit is free; you ___ pay.",("don't have to","mustn't","shouldn't to"),"don't have to"),("listening","detail","Which symptom does the patient have?",("a headache","a cough","a broken arm"),"a headache"),("listening","advice","What does the doctor suggest first?",("rest and water","running","staying awake"),"rest and water"),("reading","reference","What does 'it' in 'It says students…' refer to?",("the poster","the class","the screen"),"the poster"),("writing","tone","Choose friendly general advice.",("You should take a short break.","I diagnose your illness.","You must be healthy now."),"You should take a short break."),("speaking","role-play","Patient: I feel tired. Doctor: ___.",("You should rest.","You rested tomorrow.","You mustn't sleep ever."),"You should rest.")),
    },
    6: {
        "title":"Shopping Smart","ar":"تسوّق بذكاء","theme":"shopping-comparisons",
        "words":(("price","سعر"),("size","مقاس"),("product","منتج"),("discount","خصم"),("receipt","إيصال"),("cheap","رخيص"),("expensive","غالي"),("quality","جودة"),("enough","كافٍ"),("customer","عميل")),
        "grammar":("Comparing products and quantities","Comparatives compare two things; superlatives identify one extreme in a group.","Use -er/more, -est/most, too/enough, and quantity words that match countable or uncountable nouns.","cheaper than; the most useful; too expensive; enough money",("This bag is cheaper than that one.","It is the lightest phone here.","We have a few sizes but not much time."),("more cheaper → cheaper","the most cheap → the cheapest","many money → much money"),"a few/many + countable; a little/much + uncountable.","Which option is light enough and less expensive?"),
        "dialogue":(("Customer","Do you have this jacket in a larger size?"),("Salesperson","Yes. The blue one is larger and cheaper, but the black one is warmer."),("Customer","I have enough money for either. Which is the most popular?"),("Salesperson","The black one, and it has a ten-percent discount today.")),
        "audio":"A customer compares two jackets. The blue jacket is larger and cheaper. The warmer black jacket is more popular and discounted.",
        "read":("Three study lamps","Lamp A costs 60 riyals and is the cheapest, but its light is not bright enough for a large desk. Lamp B costs 85 riyals, has three light settings, and uses less energy than Lamp A. Lamp C is the most expensive at 110 riyals. It is also the largest. For a small study desk, reviewers say Lamp B offers the best balance of price and quality."),
        "writing":("Compare three products and recommend one.","Lamp B is more expensive than Lamp A, but it has better features. Lamp C is the largest and most expensive. I recommend Lamp B because it is useful enough and its price is reasonable.",( "…is cheaper than…","the most…","…enough for…","I recommend… because…")),
        "mission":"Compare three products by price, quality, and suitability; choose one.","review":("A1.3 plurals","A1.6 some/any and count nouns"),"support":"optional",
        "mcq":(("vocabulary","shopping","A paper showing what you paid is a ___.",("receipt","discount","size"),"receipt"),("vocabulary","value","A lower special price is a ___.",("discount","quality","customer"),"discount"),("grammar","comparative","This phone is ___ than that one.",("lighter","lightest","more light"),"lighter"),("grammar","superlative","It is ___ bag in the shop.",("the cheapest","cheaper","most cheap"),"the cheapest"),("grammar","quantity","We have ___ time, but only ___ products to compare.",("a little / a few","a few / much","many / a little"),"a little / a few"),("listening","detail","Which jacket is cheaper?",("the blue one","the black one","both cost the same"),"the blue one"),("listening","number","What is today's discount?",("ten percent","twenty percent","five riyals"),"ten percent"),("reading","inference","Which lamp suits a small study desk best?",("Lamp B","Lamp A","Lamp C"),"Lamp B"),("writing","recommendation","Choose the clearest recommendation.",("I recommend B because it balances price and quality.","B recommend cheapest than.","Because product enough."),"I recommend B because it balances price and quality."),("speaking","shop-request","Choose the polite customer request.",("Could I try a larger size, please?","Give larger now.","I larger size."),"Could I try a larger size, please?")),
    },
    7: {
        "title":"Travel & Transport","ar":"السفر والمواصلات","theme":"travel-booking",
        "words":(("airport","مطار"),("station","محطة"),("ticket","تذكرة"),("flight","رحلة جوية"),("hotel","فندق"),("reservation","حجز"),("departure","مغادرة"),("arrival","وصول"),("platform","رصيف"),("luggage","أمتعة")),
        "grammar":("Travel language review","Travel tasks combine time, place, past events, and future arrangements.","Use at/on/in accurately and select past or future forms from the travel context.","at 8:00; on platform 3; in July; going to depart",("The train leaves at 8:15.","We waited on platform four.","I'm going to book a hotel tonight."),("in platform → on platform","at Monday → on Monday","We going to travel → We're going to travel"),"Read timetable facts in Present Simple; use going to for personal plans.","What time does the flight depart?"),
        "dialogue":(("Traveller","I'd like to confirm my reservation to Jeddah."),("Agent","Your flight departs at 14:20 from Gate 8. Check-in closes at 13:35."),("Traveller","Can I take two bags?"),("Agent","One suitcase and one small bag. Please arrive early.")),
        "audio":"A traveller confirms a Jeddah flight. Departure is at 14:20 from Gate 8, while check-in closes at 13:35. The traveller may take one suitcase and one small bag.",
        "read":("Weekend rail booking","Booking: Riyadh to Hofuf, Saturday 12 October. Outbound train 108 leaves Riyadh at 07:40 and arrives at 10:05. Seat 14A, Coach 3. Return train 117 departs at 18:30 on Sunday. Changes are free until 24 hours before departure. Passengers should reach the platform at least 20 minutes early."),
        "writing":("Write a short travel plan using booking details.","On Saturday, I'm taking train 108 to Hofuf. It leaves Riyadh at 7:40 and arrives at 10:05. My seat is 14A. I am going to reach the platform twenty minutes early.",( "It leaves at…","It arrives at…","My reservation is…","I'm going to…")),
        "mission":"Plan a short trip and complete a booking-information role-play.","review":("A1.8 directions and prepositions","A1.10 past events","A2.4 future plans"),"support":"minimal-on-demand",
        "mcq":(("vocabulary","airport","The time a plane leaves is its ___.",("departure","arrival","luggage"),"departure"),("vocabulary","rail","You wait for a train on the ___.",("platform","hotel","flight"),"platform"),("grammar","time-preposition","The flight leaves ___ 14:20.",("at","on","in"),"at"),("grammar","future-plan","We ___ book the hotel tonight; it is our plan.",("are going to","did","have yesterday"),"are going to"),("grammar","timetable","The train ___ at 7:40 tomorrow.",("leaves","is leave","left yesterday"),"leaves"),("listening","number","When does check-in close?",("13:35","14:20","Gate 8"),"13:35"),("listening","allowance","What luggage is allowed?",("one suitcase and one small bag","two suitcases","no bags"),"one suitcase and one small bag"),("reading","specific-detail","Where is seat 14A?",("Coach 3","platform 20","train 117"),"Coach 3"),("reading","inference","When should the passenger reach the platform?",("by 07:20","at 07:40","after 08:00"),"by 07:20"),("speaking","information-request","Choose the clearest travel question.",("Which platform does the train leave from?","Where platform train?","The platform is why?"),"Which platform does the train leave from?")),
    },
    8: {
        "title":"Technology & Communication","ar":"التقنية والتواصل","theme":"digital-instructions",
        "words":(("device","جهاز"),("account","حساب"),("password","كلمة مرور"),("website","موقع"),("download","ينزّل"),("upload","يرفع"),("message","رسالة"),("attach","يرفق"),("screen","شاشة"),("connection","اتصال")),
        "grammar":("Instructions and simple relative clauses","Imperatives tell someone what to do; sequence words make steps easy to follow.","Start instructions with a base verb. Use who for people and which/that for things.","First, open…; the app that…; a person who…",("First, open the website.","Choose a password that is hard to guess.","Ask a person who manages the account."),("First you opening → First, open","a device who → a device that","Finally to click → Finally, click"),"who = people; which/that = things.","Put these actions in a safe, logical order."),
        "dialogue":(("Nadia","How do I upload this document?"),("Omar","First, open the class website and sign in. Next, choose the page that says Assignments."),("Nadia","Do I click the blue button?"),("Omar","Yes. Then attach the file, and finally check the filename before you send it.")),
        "audio":"Omar explains how to upload a document: sign in, open Assignments, attach the file, check its name, and send it.",
        "read":("Resetting an account password","If you cannot sign in, first open the account page and select 'Forgot password'. Next, enter the email that you used to create the account. The website will send a message with a temporary link. Open the link, create a strong new password, and do not share it. Finally, sign in again. Contact the support person who manages the website if the message does not arrive."),
        "writing":("Write clear instructions for one simple digital task.","First, open the app and choose New Message. Next, enter the address of the person who will receive it. Then write a clear subject and attach the file. Finally, check everything and press Send.",( "First,…","Next,…","Then,…","Finally,…","…that…")),
        "mission":"Explain a digital task so a partner can complete it without guessing.","review":("A1.9 imperatives and requests","A2.3 past participles"),"support":"minimal-on-demand",
        "mcq":(("vocabulary","files","To add a file to a message, you ___ it.",("attach","download","connect"),"attach"),("vocabulary","security","A secret used to enter an account is a ___.",("password","screen","website"),"password"),("grammar","imperative","Choose the correct instruction.",("Open the website.","You opening website.","To opened the website."),"Open the website."),("grammar","relative-things","Use an app ___ protects your data.",("that","who","where person"),"that"),("grammar","relative-people","Ask the person ___ manages the account.",("who","which","that device"),"who"),("listening","sequence","What happens after opening Assignments?",("attach the file","create an account","close the screen"),"attach the file"),("listening","detail","What should Nadia check before sending?",("the filename","the screen size","the password age"),"the filename"),("reading","sequence","What does the website send?",("a temporary link","a new device","a public password"),"a temporary link"),("reading","inference","Who should you contact if no message arrives?",("the support person","every user","a shop customer"),"the support person"),("writing","cohesion","Choose the best final step.",("Finally, check the details and send.","First finally sending.","Who send next device."),"Finally, check the details and send.")),
    },
    9: {
        "title":"Stories & Events","ar":"القصص والأحداث","theme":"connected-stories",
        "words":(("notice","يلاحظ"),("continue","يستمر"),("interrupt","يقاطع"),("worried","قلق"),("relieved","مرتاح"),("crowd","حشد"),("while","بينما"),("although","مع أن"),("eventually","في النهاية"),("escape","يفلت")),
        "grammar":("Past Simple and Past Continuous","Past Continuous creates the background; Past Simple reports the shorter event that changed it.","Use when for an interrupting event and while for two background actions. Connect reasons and contrasts clearly.","was/were + verb-ing; past verb",("I was waiting when the bus arrived.","While they were walking, it started to rain.","Although she was worried, she stayed calm."),("I was wait → I was waiting","When I was arrived → When I arrived","While the phone rang → While I was studying, the phone rang"),"because gives a reason; so gives a result; but/although show contrast.","What was happening when the main event occurred?"),
        "dialogue":(("Reporter","What were you doing when the alarm started?"),("Witness","I was buying a ticket while my brother was waiting outside."),("Reporter","What happened next?"),("Witness","Everyone left calmly. We were worried, but staff explained it was only a test.")),
        "audio":"A witness was buying a ticket when an alarm started. People left calmly. They felt worried at first, but staff said the alarm was only a test.",
        "read":("The bag on the bus","Leen was travelling home when she noticed a bag under an empty seat. The bus was moving through heavy traffic, so she could not speak to the driver immediately. While she was deciding what to do, an older passenger began looking around nervously. Leen asked whether the bag was his. He looked relieved because it contained important papers. Although he nearly missed his stop, he thanked Leen before leaving. Leen felt pleased that she had asked a simple question."),
        "writing":("Write a short story with background, an interruption, and an ending.","I was walking home when I heard a strange sound. While I was looking for it, a small cat came out from behind a wall. It was wet because it had been in the rain, so I called my neighbour. Eventually, we found its owner.",( "I was … when…","While…","because… so…","Eventually,…")),
        "mission":"Tell a story in order and make the background and main events clear.","review":("A1.10 Past Simple","A2.2 story sequence"),"support":"minimal-on-demand",
        "mcq":(("vocabulary","feelings","After finding her lost keys, she felt ___.",("relieved","worried","interrupted"),"relieved"),("vocabulary","sequence","A word meaning 'after some time, in the end' is ___.",("eventually","while","although"),"eventually"),("grammar","background-interruption","I ___ home when it started to rain.",("was walking","walked always","am walking yesterday"),"was walking"),("grammar","while","While we ___, the lights went out.",("were eating","ate suddenly","are eat"),"were eating"),("grammar","connector","He was tired, ___ he continued.",("but","so that result","because result"),"but"),("listening","main-idea","Why did people leave?",("an alarm started","the bus arrived","tickets sold out"),"an alarm started"),("listening","speaker-feeling","How did the witness feel before the explanation?",("worried","bored","excited"),"worried"),("reading","reference","Who does 'he' in 'whether the bag was his' refer to?",("the older passenger","the driver","Leen"),"the older passenger"),("reading","inference","Why couldn't Leen speak to the driver immediately?",("The bus was moving in traffic.","She had left the bus.","The driver found the bag."),"The bus was moving in traffic."),("writing","story-order","Choose the strongest opening.",("I was waiting when I heard a shout.","Eventually first because.","I hear yesterday while now."),"I was waiting when I heard a shout.")),
    },
    10: {
        "title":"Real English","ar":"إنجليزية واقعية","theme":"integrated-communication",
        "words":(("confirm","يؤكد"),("recommend","يوصي"),("available","متاح"),("instead","بدلًا من ذلك"),("prefer","يفضّل"),("problem","مشكلة"),("solution","حل"),("appointment","موعد"),("order","طلب"),("detail","تفصيل")),
        "grammar":("A2 language in real situations","Real communication requires choosing familiar language for the situation, time, and purpose.","Combine questions, past reports, current needs, and future plans without translating every sentence.","choose the form that carries the intended meaning",("I'd like to confirm my reservation.","I ordered soup, but this is salad.","I'm going to meet them after lunch."),("I want confirm → I'd like to confirm","I did ordered → I ordered","I going meet → I'm going to meet"),"Use polite requests for service; give precise facts when reporting a problem.","Listen, identify the goal, then choose the shortest clear response."),
        "dialogue":(("Guest","Hello. I'd like to confirm a table for three at seven."),("Host","I can see a booking for two. Would a table for three at seven thirty be acceptable?"),("Guest","Yes, that works. One guest doesn't eat meat. Is a vegetarian meal available?"),("Host","Certainly. I'll add that detail to your reservation.")),
        "audio":"A guest calls a restaurant about a reservation. The original booking is for two at seven. They agree to a table for three at seven thirty and request a vegetarian option.",
        "read":("A day of small changes","Khalid planned to take the 9:00 train for a work meeting, but it was cancelled. He asked the station assistant for help and booked the 9:40 service instead. While he was waiting, he emailed his colleague to explain the delay. He has used that route many times, but this was his first cancellation. He arrived fifteen minutes late, apologised, and completed the meeting. Before returning home, he confirmed his evening restaurant reservation."),
        "writing":("Write a practical message that explains a change and proposes a solution.","Hello Sara, my train was cancelled, so I am going to arrive about fifteen minutes late. Could we meet at 10:15 instead? I have already sent the updated document. Please let me know if the new time is a problem.",( "The problem is…","Could we … instead?","I have already…","Please let me know…")),
        "mission":"Complete one full scenario: resolve a booking problem, explain what happened, and agree on a new plan.","review":("A1 everyday communication","A2 past, present perfect, and future","A2 polite functional language"),"support":"english-first",
        "mcq":(("vocabulary","problem-solving","A good answer to a problem is a ___.",("solution","detail","order"),"solution"),("vocabulary","service","To check that a booking is correct, you ___ it.",("confirm","prefer","interrupt"),"confirm"),("grammar","polite-request","Choose the most suitable restaurant request.",("I'd like to confirm my table, please.","Confirm table now.","I confirmed tomorrow."),"I'd like to confirm my table, please."),("grammar","past-report","The train ___, so I booked another one.",("was cancelled","is cancelling yesterday","has cancel last Monday"),"was cancelled"),("grammar","future-solution","We ___ meet at 10:15 instead.",("could","did","have ever"),"could"),("listening","detail","What was wrong with the original booking?",("It was for two people.","It was at seven thirty.","There was no booking."),"It was for two people."),("listening","outcome","What time do they finally agree on?",("7:30","7:00","9:40"),"7:30"),("reading","sequence","What did Khalid do after booking the later train?",("emailed his colleague","cancelled the meeting","ordered dinner"),"emailed his colleague"),("reading","inference","Why was the cancellation unusual for Khalid?",("It was his first on that familiar route.","He never takes trains.","He arrived early."),"It was his first on that familiar route."),("writing","functional-response","Choose the clearest solution message.",("I'm delayed; could we meet at 10:15 instead?","Delay because meeting maybe.","Yesterday I will arrive."),"I'm delayed; could we meet at 10:15 instead?")),
    },
}


def _vocabulary(spec):
    result = []
    for index, (english, arabic) in enumerate(spec["words"]):
        result.append(w(english, arabic, f"Use '{english}' in a useful {spec['theme'].replace('-', ' ')} sentence.", f"استخدم «{arabic}» في جملة مفيدة.", spec["theme"], f"use {english}" if index % 2 else f"common {english}"))
    return tuple(result)


def _questions(spec, order):
    result = []
    for index, (skill, subskill, prompt, choices, answer) in enumerate(spec["mcq"], 1):
        difficulty = 2 + (order >= 4) + (order >= 8 and index % 3 != 0)
        difficulty = min(difficulty, 4)
        result.append(q(f"q{index}", skill, subskill, difficulty, prompt, choices, answer,
            f"'{answer}' fits both the meaning and form required by this context.",
            "Read the whole context and identify its time, purpose, or key detail.",
            f"Try again with the same skill: {prompt}", answer))
    return tuple(result)


def build_a2_unit(order):
    spec = SPECS[order]
    grammar = spec["grammar"]
    dialogue = spec["dialogue"]
    listening_questions = (
        aq("What is the conversation mainly about?", (spec["theme"].replace("-", " "), "a weather report", "a sports result"), spec["theme"].replace("-", " ")),
        aq("Which detail is stated?", (spec["audio"].split(". ")[0] + ".", "No details are provided.", "The speakers disagree about everything."), spec["audio"].split(". ")[0] + "."),
        aq("What should the listener do?", ("connect the details in order", "ignore times and reasons", "translate only one word"), "connect the details in order"),
    )
    reading_title, passage = spec["read"]
    reading_questions = (
        aq("What is the text mainly about?", (spec["theme"].replace("-", " "), "an unrelated recipe", "a weather forecast"), spec["theme"].replace("-", " ")),
        aq("Which reading strategy helps with this text?", ("follow times, reasons, and results", "read only the title", "ignore linking words"), "follow times, reasons, and results"),
        aq("Which statement is supported by the passage?", (passage.split(". ")[0] + ".", "The opposite of every detail is true.", "No event or action is mentioned."), passage.split(". ")[0] + "."),
    )
    writing_task, model, phrases = spec["writing"]
    games = (
        game(f"detect-{order}", "grammar_detective", "Grammar Detective", "Choose the form that fits the situation.", spec["mcq"][2][2], spec["mcq"][2][3], spec["mcq"][2][4]),
        game(f"order-{order}", "story_order" if order in (2, 9) else "conversation_builder", "Meaning Builder", "Connect language to a realistic purpose.", spec["mcq"][5][2], spec["mcq"][5][3], spec["mcq"][5][4]),
        game(f"sprint-{order}", "true_false_sprint" if order % 2 else "quick_choice", "Quick Choice", "Notice a precise detail under light time pressure.", spec["mcq"][7][2], spec["mcq"][7][3], spec["mcq"][7][4]),
    )
    return unit(
        code=f"A2.{order}", title=spec["title"], arabic_title=spec["ar"], theme=spec["theme"],
        objectives=(f"Use language for {spec['theme'].replace('-', ' ')}", "Connect information across longer messages", "Respond with increasing independence"),
        can_do=(f"I can communicate about {spec['theme'].replace('-', ' ')}.", "I can understand and create a connected A2 response."),
        vocabulary=_vocabulary(spec),
        grammar={"title":grammar[0],"meaning":grammar[1],"use":grammar[2],"form":grammar[3],"explanation_en":f"{grammar[1]} {grammar[2]}","explanation_ar":"شرح عربي اختياري يوضح المعنى والاستخدام، مع إبقاء الإنجليزية أولًا.","examples":grammar[4],"common_mistakes":grammar[5],"comparison":grammar[6],"quick_check":grammar[7],"tips":("Choose from meaning before form.","Read the entire sentence before answering.")},
        listening={"pre_listening":f"What information do you expect in a conversation about {spec['theme'].replace('-', ' ')}?","dialogue":dialogue,"audio_text":spec["audio"],"transcript":dialogue,"hide_transcript_until_attempt":True,"questions":listening_questions},
        speaking={"shadowing":tuple(line for _, line in dialogue)[:4],"pronunciation_practice":("Stress the important content words.","Pause between connected ideas.","Use a polite, clear tone."),"role_play":dialogue,"guided":phrases,"independent":spec["mission"],"prompts":("Give the key information.","Ask and answer one follow-up question.")},
        reading={"type":"authored A2 text","title":reading_title,"passage":passage,"arabic_support":"ملخص عربي اختياري يظهر عند الطلب فقط.","questions":reading_questions},
        writing={"task":writing_task,"model":model,"useful_phrases":phrases,"checklist":("Address the task fully.","Connect ideas clearly.","Check the target grammar.","Check spelling and punctuation."),"scaffold":phrases[:max(1, 5-order//2)],"optional_challenge":"Add one useful detail and a natural follow-up question."},
        games=games,
        mission={"title":spec["title"]+" Mission","real_world_task":spec["mission"],"steps":("Prepare key words, not a full script.","Complete the situation.","Respond to one change or follow-up."),"success_criteria":("The message is clear.","The target language supports the real purpose.")},
        quiz=_questions(spec, order), review_from=spec["review"], arabic_support=spec["support"],
    )
