warning: in the working copy of 'build.sh', LF will be replaced by CRLF the next time Git touches it
[1mdiff --git a/abcz/settings.py b/abcz/settings.py[m
[1mindex 6b7c95c..ad0b2cb 100644[m
[1m--- a/abcz/settings.py[m
[1m+++ b/abcz/settings.py[m
[36m@@ -1,7 +1,7 @@[m
 """[m
 Django settings for abcz project.[m
[31m-[m
 Generated by 'django-admin startproject' using Django 5.2.4.[m
[32m+[m[32mProduction-ready for Render + WhiteNoise + Postgres[m
 """[m
 [m
 from pathlib import Path[m
[36m@@ -13,40 +13,56 @@[m [mimport dj_database_url[m
 # ==========================[m
 BASE_DIR = Path(__file__).resolve().parent.parent[m
 [m
[32m+[m
 # ==========================[m
 # مفاتيح وأوضاع التشغيل[m
 # ==========================[m
[31m-[m
[31m-# SECRET_KEY:[m
[31m-# في الإنتاج يفضّل وضعه في متغير بيئة باسم SECRET_KEY[m
 SECRET_KEY = os.getenv([m
     "SECRET_KEY",[m
[31m-    "django-insecure-^8&_75zy-la0_m52)(d8k(ose8ug%%7i&nrqpgf0vywus^qce-",[m
[32m+[m[32m    "django-insecure-CHANGE-ME-IN-PRODUCTION",[m
 )[m
 [m
[31m-# DEBUG من متغير بيئة، افتراضيًا True في جهازك، False في Render[m
[31m-DEBUG = os.getenv("DEBUG", "True") == "True"[m
[32m+[m[32m# اجعلي DEBUG افتراضيًا False في Render، True محليًا فقط[m
[32m+[m[32m# (Render عادة يضبط DEBUG في Environment)[m
[32m+[m[32mDEBUG = os.getenv("DEBUG", "False").strip().lower() in ("1", "true", "yes", "on")[m
 [m
 # ==========================[m
 # السماح بالمضيفين (ALLOWED_HOSTS)[m
 # ==========================[m
[32m+[m[32m# دعم Render تلقائياً إذا كان متغير RENDER_EXTERNAL_HOSTNAME موجود[m
[32m+[m[32mRENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")[m
 [m
[31m-# دومين Render + المحلي[m
 ALLOWED_HOSTS = [[m
[31m-    "abcz-epbz.onrender.com",[m
     "localhost",[m
     "127.0.0.1",[m
 ][m
 [m
[32m+[m[32m# دومينك الحالي في Render[m
[32m+[m[32mALLOWED_HOSTS.append("abcz-epbz.onrender.com")[m
[32m+[m
[32m+[m[32m# إذا Render عطاك hostname تلقائياً[m
[32m+[m[32mif RENDER_EXTERNAL_HOSTNAME:[m
[32m+[m[32m    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)[m
[32m+[m
[32m+[m[32m# لو حابة تستخدمين متغير بيئة ALLOWED_HOSTS كسطر مفصول بفواصل[m
[32m+[m[32m# مثال في Render: ALLOWED_HOSTS=abcz-epbz.onrender.com,example.com[m
[32m+[m[32mextra_hosts = os.getenv("ALLOWED_HOSTS", "").strip()[m
[32m+[m[32mif extra_hosts:[m
[32m+[m[32m    for h in extra_hosts.split(","):[m
[32m+[m[32m        h = h.strip()[m
[32m+[m[32m        if h and h not in ALLOWED_HOSTS:[m
[32m+[m[32m            ALLOWED_HOSTS.append(h)[m
[32m+[m
 # حتى تعمل POST/CSRF بشكل صحيح على Render[m
 CSRF_TRUSTED_ORIGINS = [[m
     "https://abcz-epbz.onrender.com",[m
 ][m
[32m+[m[32mif RENDER_EXTERNAL_HOSTNAME:[m
[32m+[m[32m    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")[m
 [m
 # ==========================[m
 # التطبيقات[m
 # ==========================[m
[31m-[m
 INSTALLED_APPS = [[m
     "django.contrib.admin",[m
     "django.contrib.auth",[m
[36m@@ -54,10 +70,12 @@[m [mINSTALLED_APPS = [[m
     "django.contrib.sessions",[m
     "django.contrib.messages",[m
     "django.contrib.staticfiles",[m
[31m-    # تطبيق الألعاب[m
     "phonics",[m
 ][m
 [m
[32m+[m[32m# ==========================[m
[32m+[m[32m# الميدلوير[m
[32m+[m[32m# ==========================[m
 MIDDLEWARE = [[m
     "django.middleware.security.SecurityMiddleware",[m
     # WhiteNoise لملفات الستاتيك في Render[m
[36m@@ -89,21 +107,23 @@[m [mTEMPLATES = [[m
 [m
 WSGI_APPLICATION = "abcz.wsgi.application"[m
 [m
[32m+[m
 # ==========================[m
 # قاعدة البيانات[m
 # ==========================[m
[32m+[m[32mDATABASE_URL = os.getenv("DATABASE_URL", "").strip()[m
 [m
[31m-# إذا وجد DATABASE_URL (على Render) → استخدم Postgres[m
[31m-# غير ذلك → SQLite محليًا[m
[31m-if os.getenv("DATABASE_URL"):[m
[32m+[m[32mif DATABASE_URL:[m
[32m+[m[32m    # Postgres on Render[m
     DATABASES = {[m
         "default": dj_database_url.config([m
[31m-            default=os.getenv("DATABASE_URL"),[m
[32m+[m[32m            default=DATABASE_URL,[m
             conn_max_age=600,[m
             ssl_require=True,[m
         )[m
     }[m
 else:[m
[32m+[m[32m    # SQLite locally[m
     DATABASES = {[m
         "default": {[m
             "ENGINE": "django.db.backends.sqlite3",[m
[36m@@ -111,39 +131,31 @@[m [melse:[m
         }[m
     }[m
 [m
[32m+[m
 # ==========================[m
 # كلمات المرور[m
 # ==========================[m
[31m-[m
 AUTH_PASSWORD_VALIDATORS = [[m
[31m-    {[m
[31m-        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",[m
[31m-    },[m
[31m-    {[m
[31m-        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",[m
[31m-    },[m
[31m-    {[m
[31m-        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",[m
[31m-    },[m
[31m-    {[m
[31m-        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",[m
[31m-    },[m
[32m+[m[32m    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},[m
[32m+[m[32m    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},[m
[32m+[m[32m    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},[m
[32m+[m[32m    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},[m
 ][m
 [m
[32m+[m
 # ==========================[m
 # اللغة والوقت[m
 # ==========================[m
[31m-[m
[31m-LANGUAGE_CODE = "en-us"   # غيّريها لـ 'ar' لو حبيتي[m
[31m-TIME_ZONE = "UTC"[m
[32m+[m[32mLANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "en-us")[m
[32m+[m[32mTIME_ZONE = os.getenv("TIME_ZONE", "UTC")[m
 [m
 USE_I18N = True[m
 USE_TZ = True[m
 [m
[32m+[m
 # ==========================[m
[31m-# ملفات الستاتيك[m
[32m+[m[32m# ملفات الستاتيك (Static)[m
 # ==========================[m
[31m-[m
 STATIC_URL = "/static/"[m
 [m
 # مكان تجميع ملفات الستاتيك في الإنتاج (Render)[m
[36m@@ -154,11 +166,33 @@[m [mSTATICFILES_DIRS = [[m
     BASE_DIR / "static",[m
 ][m
 [m
[31m-# ضغط الكاش للستاتيك مع WhiteNoise[m
[32m+[m[32m# WhiteNoise: ضغط + manifest (ممتاز للإنتاج)[m
 STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"[m
 [m
[32m+[m
 # ==========================[m
[31m-# الإعداد الافتراضي لمفاتيح PK[m
[32m+[m[32m# إعدادات أمان للإنتاج (مهم)[m
 # ==========================[m
[32m+[m[32m# Render خلف HTTPS: فعلّي هذا في الإنتاج فقط[m
[32m+[m[32mSECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")[m
[32m+[m
[32m+[m[32mif not DEBUG:[m
[32m+[m[32m    SESSION_COOKIE_SECURE = True[m
[32m+[m[32m    CSRF_COOKIE_SECURE = True[m
[32m+[m[32m    SECURE_SSL_REDIRECT = True[m
[32m+[m
[32m+[m[32m    # HSTS (اختياري لكنه قوي)[m
[32m+[m[32m    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "86400"))  # يوم[m
[32m+[m[32m    SECURE_HSTS_INCLUDE_SUBDOMAINS = True[m
[32m+[m[32m    SECURE_HSTS_PRELOAD = True[m
[32m+[m
[32m+[m[32m    # حماية إضافية[m
[32m+[m[32m    SECURE_CONTENT_TYPE_NOSNIFF = True[m
[32m+[m[32m    SECURE_REFERRER_POLICY = "same-origin"[m
[32m+[m[32m    X_FRAME_OPTIONS = "DENY"[m
 [m
[32m+[m
[32m+[m[32m# ==========================[m
[32m+[m[32m# الإعداد الافتراضي لمفاتيح PK[m
[32m+[m[32m# ==========================[m
 DEFAULT_AUTO_