"""
Django settings for abcz project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os
import dj_database_url

# ==========================
# المسارات الأساسية
# ==========================
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================
# مفاتيح وأوضاع التشغيل
# ==========================

# SECRET_KEY:
# في الإنتاج يفضّل وضعه في متغير بيئة باسم SECRET_KEY
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-^8&_75zy-la0_m52)(d8k(ose8ug%%7i&nrqpgf0vywus^qce-",
)

# DEBUG من متغير بيئة، افتراضيًا True في جهازك، False في Render
DEBUG = os.getenv("DEBUG", "True") == "True"

# ==========================
# السماح بالمضيفين (ALLOWED_HOSTS)
# ==========================

# دومين Render + المحلي
ALLOWED_HOSTS = [
    "abcz-epbz.onrender.com",
    "localhost",
    "127.0.0.1",
]

# حتى تعمل POST/CSRF بشكل صحيح على Render
CSRF_TRUSTED_ORIGINS = [
    "https://abcz-epbz.onrender.com",
]

# ==========================
# التطبيقات
# ==========================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # تطبيق الألعاب
    "phonics",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise لملفات الستاتيك في Render
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "abcz.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # مجلد templates الرئيسي
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "abcz.wsgi.application"

# ==========================
# قاعدة البيانات
# ==========================

# إذا وجد DATABASE_URL (على Render) → استخدم Postgres
# غير ذلك → SQLite محليًا
if os.getenv("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# ==========================
# كلمات المرور
# ==========================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ==========================
# اللغة والوقت
# ==========================

LANGUAGE_CODE = "en-us"   # غيّريها لـ 'ar' لو حبيتي
TIME_ZONE = "UTC"

USE_I18N = True
USE_TZ = True

# ==========================
# ملفات الستاتيك
# ==========================

STATIC_URL = "/static/"

# مكان تجميع ملفات الستاتيك في الإنتاج (Render)
STATIC_ROOT = BASE_DIR / "staticfiles"

# لو عندك مجلد static في المشروع
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ضغط الكاش للستاتيك مع WhiteNoise
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ==========================
# الإعداد الافتراضي لمفاتيح PK
# ==========================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
