"""
Django settings for abcz project.
Generated by 'django-admin startproject' using Django 5.2.4.
Production-ready for Render + WhiteNoise + Postgres
"""

from pathlib import Path
import os
import dj_database_url

# ==========================
# المسارات الأساسية
# ==========================
BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================
# مفاتيح وأوضاع التشغيل
# ==========================
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-CHANGE-ME-IN-PRODUCTION",
)

# اجعلي DEBUG افتراضيًا False في Render، True محليًا فقط
# (Render عادة يضبط DEBUG في Environment)
DEBUG = os.getenv("DEBUG", "False").strip().lower() in ("1", "true", "yes", "on")

# ==========================
# السماح بالمضيفين (ALLOWED_HOSTS)
# ==========================
# دعم Render تلقائياً إذا كان متغير RENDER_EXTERNAL_HOSTNAME موجود
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

# دومينك الحالي في Render
ALLOWED_HOSTS.append("abcz-epbz.onrender.com")

# إذا Render عطاك hostname تلقائياً
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# لو حابة تستخدمين متغير بيئة ALLOWED_HOSTS كسطر مفصول بفواصل
# مثال في Render: ALLOWED_HOSTS=abcz-epbz.onrender.com,example.com
extra_hosts = os.getenv("ALLOWED_HOSTS", "").strip()
if extra_hosts:
    for h in extra_hosts.split(","):
        h = h.strip()
        if h and h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(h)

# حتى تعمل POST/CSRF بشكل صحيح على Render
CSRF_TRUSTED_ORIGINS = [
    "https://abcz-epbz.onrender.com",
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

# ==========================
# التطبيقات
# ==========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "phonics",
]

# ==========================
# الميدلوير
# ==========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise لملفات الستاتيك في Render
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "abcz.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # مجلد templates الرئيسي
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "abcz.wsgi.application"


# ==========================
# قاعدة البيانات
# ==========================
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if DATABASE_URL:
    # Postgres on Render
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    # SQLite locally
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# ==========================
# كلمات المرور
# ==========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ==========================
# اللغة والوقت
# ==========================
LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "en-us")
TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True
USE_TZ = True


# ==========================
# ملفات الستاتيك (Static)
# ==========================
STATIC_URL = "/static/"

# مكان تجميع ملفات الستاتيك في الإنتاج (Render)
STATIC_ROOT = BASE_DIR / "staticfiles"

# لو عندك مجلد static في المشروع
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise: ضغط + manifest (ممتاز للإنتاج)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ==========================
# إعدادات أمان للإنتاج (مهم)
# ==========================
# إعدادات آمنة ومرنة حسب البيئة
# في التطوير: جميع إعدادات HTTPS مُعطلة
# في الإنتاج: جميع إعدادات HTTPS مُفعّلة

# تفعيل SSL Redirect فقط في الإنتاج وعند الطلب صراحة
SECURE_SSL_REDIRECT = (not DEBUG) and (os.getenv("SECURE_SSL_REDIRECT", "0") == "1")

# Cookies آمنة فقط في الإنتاج
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Proxy SSL Header فقط في الإنتاج (Render خلف HTTPS)
SECURE_PROXY_SSL_HEADER = None if DEBUG else ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    # HSTS (اختياري لكنه قوي)
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "86400"))  # يوم
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # حماية إضافية
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"


# ==========================
# الإعداد الافتراضي لمفاتيح PK
# ==========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
